version: "3.8"

services:
  pms-redis:
    image: redis:7-alpine
    container_name: pms-redis
    restart: always
    networks:
      - thaimui

  thaimui-pms-api:
    build : .
    platform: linux/amd64
    image: registry.gitlab.com/jostechnology/thaimui-pms-api-dev:thaimui-1.0.23
    container_name: thaimui-pms-api
    restart: always

    ports:
      - "8002:5000"

    environment:
      - connection_string=${connection_string}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CENTER_ACCESS_KEY=${CENTER_ACCESS_KEY}
      - CENTER_URL=${CENTER_URL}
      - DOCUMENT_GENERATOR_URL=${DOCUMENT_GENERATOR_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_SECURE=${MINIO_SECURE}
      - REDIS_URL=${REDIS_URL}
      - WMS_URL=${WMS_URL}
    
    networks:
      - thaimui

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"

networks:
  thaimui:
    external: true
