version: "3.8"

services:
  thaimui-pms-api:
    platform: linux/amd64
    image: registry.gitlab.com/jostechnology/thaimui-pms-api-dev:${TAG}
    container_name: thaimui-pms-api
    restart: always

    ports:
      - "8002:5000"

    environment:
      - connection_string=${connection_string}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CENTER_ACCESS_KEY=${CENTER_ACCESS_KEY}
      - CENTER_URL=${CENTER_URL}
    
    networks:
      - thaimui

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"

networks:
  thaimui:
    external: true
