version: "3.8"
services:
  api:
    image: registry.gitlab.com/jaoaurai/container-registry/thaimui-pms-api-dev:${TAG}
    container_name: thaimui-pms-api
    restart: always
    network_mode: bridge

    ports:
      - 5000:5000
    environment:

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"