"""branch_to_other_entities

Revision ID: 0031a9a756d1
Revises: 085001b57cdc
Create Date: 2026-04-04 13:55:43.949234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0031a9a756d1'
down_revision = '085001b57cdc'
branch_labels = None
depends_on = None


def _has_column(table: str, column: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return column in [col['name'] for col in inspector.get_columns(table)]


def _has_index(table: str, index_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return index_name in [idx['name'] for idx in inspector.get_indexes(table)]


def _has_foreign_key(table: str, referred_table: str, referred_column: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return any(
        fk['referred_table'] == referred_table and referred_column in fk['referred_columns']
        for fk in inspector.get_foreign_keys(table)
    )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Nullable planning-layer tables
    nullable_tables = [
        't_component_material_usage',
        't_item_component',
        't_material_list',
        't_qc_work_order',
        't_sales_items',
        't_sales_order',
        't_work_order',
    ]
    for table in nullable_tables:
        if not _has_column(table, 'branch_id'):
            with op.batch_alter_table(table, schema=None) as batch_op:
                batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
                if not _has_index(table, f'ix_{table}_branch_id'):
                    batch_op.create_index(batch_op.f(f'ix_{table}_branch_id'), ['branch_id'], unique=False)
                if not _has_foreign_key(table, 'm_branch', 'branch_id'):
                    batch_op.create_foreign_key(None, 'm_branch', ['branch_id'], ['branch_id'])

    # Non-nullable execution tables — 3-step: add nullable → update → enforce NOT NULL + FK
    non_nullable_tables = [
        't_picking_request', 't_picking_request_item',
        't_test_result', 't_test_result_item',
        't_work_assignment', 't_work_phase', 't_work_phase_break',
        't_work_run', 't_work_run_transaction',
    ]

    # Step 1: Add branch_id as nullable (no FK yet)
    for table in non_nullable_tables:
        if not _has_column(table, 'branch_id'):
            with op.batch_alter_table(table, schema=None) as batch_op:
                batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))

    # Step 2: Set existing rows to branch_id = 1
    for table in non_nullable_tables:
        op.execute(f'UPDATE {table} SET branch_id = 1 WHERE branch_id IS NULL')

    # Step 3: Enforce NOT NULL + add index and FK via raw SQL (avoids batch copy-and-rename issues)
    op.execute('SET FOREIGN_KEY_CHECKS = 0')
    for table in non_nullable_tables:
        op.execute(f'ALTER TABLE {table} MODIFY COLUMN branch_id INT NOT NULL')
        if not _has_index(table, f'ix_{table}_branch_id'):
            op.execute(f'CREATE INDEX ix_{table}_branch_id ON {table} (branch_id)')
        if not _has_foreign_key(table, 'm_branch', 'branch_id'):
            op.execute(
                f'ALTER TABLE {table} ADD CONSTRAINT fk_{table}_branch_id '
                f'FOREIGN KEY (branch_id) REFERENCES m_branch (branch_id)'
            )
    op.execute('SET FOREIGN_KEY_CHECKS = 1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_run_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_work_run_transaction_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_work_run', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_work_run_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_work_phase_break', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_work_phase_break_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_work_phase_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_work_order_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_work_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_work_assignment_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_test_result_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_test_result_item_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_test_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_test_result_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_sales_order_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_sales_items_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_qc_work_order_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_picking_request_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_picking_request_item_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_picking_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_picking_request_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_material_list_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_item_component_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('t_component_material_usage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_component_material_usage_branch_id'))
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
