"""initial

Revision ID: 008602ea2e4a
Revises: 
Create Date: 2026-02-20 13:08:00.643760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '008602ea2e4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_work_assignment_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_work_phase', ['work_phase_id'], ['work_phase_id'], ondelete='CASCADE')

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('READY', 'INPROGRESS', 'COMPLETED', name='workorderstatus'),
               existing_nullable=False)

    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.alter_column('phase_status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'INPROGRESS', 'PAUSED', 'COMPLETED', name='phasestatus'),
               existing_nullable=False)

    with op.batch_alter_table('t_work_phase_break', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Remark', sa.String(length=255), nullable=True))
        batch_op.alter_column('break_type',
               existing_type=mysql.ENUM('LUNCH', 'SHORT_BREAK', 'OTHER'),
               type_=sa.Enum('LUNCHBREAK', 'RESTBREAK', 'OTHER', name='breaktype'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('t_work_phase_break_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_work_phase', ['work_phase_id'], ['work_phase_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase_break', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_work_phase_break_ibfk_1'), 't_work_phase', ['work_phase_id'], ['work_phase_id'])
        batch_op.alter_column('break_type',
               existing_type=sa.Enum('LUNCHBREAK', 'RESTBREAK', 'OTHER', name='breaktype'),
               type_=mysql.ENUM('LUNCH', 'SHORT_BREAK', 'OTHER'),
               existing_nullable=False)
        batch_op.drop_column('Remark')

    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.alter_column('phase_status',
               existing_type=sa.Enum('PENDING', 'INPROGRESS', 'PAUSED', 'COMPLETED', name='phasestatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('READY', 'INPROGRESS', 'COMPLETED', name='workorderstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('t_work_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_work_assignment_ibfk_1'), 't_work_phase', ['work_phase_id'], ['work_phase_id'])

    # ### end Alembic commands ###
