"""empty message

Revision ID: 055882e5a751
Revises: n8o9p0q1r2s3
Create Date: 2026-04-24 12:11:22.573029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '055882e5a751'
down_revision = 'n8o9p0q1r2s3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.drop_column('remaining_maintenance_cost')
        batch_op.drop_column('useful_life_years')
        batch_op.drop_column('working_hours_per_day')
        batch_op.drop_column('purchase_price')

    with op.batch_alter_table('t_picking_item_adjustment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counterparty_picking_request_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 't_picking_request_item', ['counterparty_picking_request_item_id'], ['picking_request_item_id'], ondelete='SET NULL')

    with op.batch_alter_table('t_picking_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reallocation', sa.Boolean(), nullable=False))

    with op.batch_alter_table('t_work_run_machine', schema=None) as batch_op:
        batch_op.drop_column('allocated_maintenance_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_run_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allocated_maintenance_cost', mysql.FLOAT(), nullable=True))

    with op.batch_alter_table('t_picking_request', schema=None) as batch_op:
        batch_op.drop_column('is_reallocation')

    with op.batch_alter_table('t_picking_item_adjustment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('counterparty_picking_request_item_id')

    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('working_hours_per_day', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('useful_life_years', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('remaining_maintenance_cost', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
