"""add purchase_price to machine

Revision ID: 05745cc2805d
Revises: d8a83ec85856
Create Date: 2026-04-21 14:50:32.686608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05745cc2805d'
down_revision = 'd8a83ec85856'
branch_labels = None
depends_on = None


def _column_exists(conn, table, column):
    result = conn.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.COLUMNS "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :t AND COLUMN_NAME = :c"
    ), {"t": table, "c": column})
    return result.scalar() > 0


def _drop_fks_on_column(conn, table, column):
    result = conn.execute(sa.text(
        "SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :t AND COLUMN_NAME = :c "
        "AND REFERENCED_TABLE_NAME IS NOT NULL"
    ), {"t": table, "c": column})
    for row in result:
        conn.execute(sa.text(f"ALTER TABLE `{table}` DROP FOREIGN KEY `{row[0]}`"))


def upgrade():
    conn = op.get_bind()

    if not _column_exists(conn, 'm_machine', 'purchase_price'):
        op.execute("ALTER TABLE m_machine ADD COLUMN purchase_price FLOAT NULL")

    if _column_exists(conn, 't_picking_item_adjustment', 'counterparty_picking_request_item_id'):
        _drop_fks_on_column(conn, 't_picking_item_adjustment', 'counterparty_picking_request_item_id')
        op.execute("ALTER TABLE t_picking_item_adjustment DROP COLUMN counterparty_picking_request_item_id")

    if _column_exists(conn, 't_picking_request', 'is_reallocation'):
        op.execute("ALTER TABLE t_picking_request DROP COLUMN is_reallocation")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_picking_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reallocation', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))

    with op.batch_alter_table('t_picking_item_adjustment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counterparty_picking_request_item_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_picking_item_adjustment_counterparty'), 't_picking_request_item', ['counterparty_picking_request_item_id'], ['picking_request_item_id'], ondelete='SET NULL')

    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.drop_column('purchase_price')

    # ### end Alembic commands ###
