"""add purchase_price to machine

Revision ID: 05745cc2805d
Revises: d8a83ec85856
Create Date: 2026-04-21 14:50:32.686608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05745cc2805d'
down_revision = 'd8a83ec85856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Float(), nullable=True))

    with op.batch_alter_table('t_picking_item_adjustment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_picking_item_adjustment_counterparty'), type_='foreignkey')
        batch_op.drop_column('counterparty_picking_request_item_id')

    with op.batch_alter_table('t_picking_request', schema=None) as batch_op:
        batch_op.drop_column('is_reallocation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_picking_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reallocation', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))

    with op.batch_alter_table('t_picking_item_adjustment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counterparty_picking_request_item_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_picking_item_adjustment_counterparty'), 't_picking_request_item', ['counterparty_picking_request_item_id'], ['picking_request_item_id'], ondelete='SET NULL')

    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.drop_column('purchase_price')

    # ### end Alembic commands ###
