"""empty message

Revision ID: 05cb554d2f09
Revises: a1e380dfbadf
Create Date: 2026-03-17 13:50:17.479123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect as sa_inspect

# revision identifiers, used by Alembic.
revision = '05cb554d2f09'
down_revision = 'a1e380dfbadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    existing_tables = sa_inspect(conn).get_table_names()

    if 'm_machine' not in existing_tables:
        op.create_table('m_machine',
        sa.Column('machine_id', sa.Integer(), nullable=False),
        sa.Column('machine_code', sa.String(length=50), nullable=False),
        sa.Column('machine_name', sa.String(length=255), nullable=False),
        sa.Column('machine_description', sa.String(length=500), nullable=True),
        sa.Column('manufacturer', sa.String(length=255), nullable=True),
        sa.Column('purchase_date', sa.DateTime(), nullable=True),
        sa.Column('status', sa.Enum('RUNNING', 'DOWN', 'IDLE', 'OFFLINE', name='machinestatus'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_by', sa.String(length=80), nullable=True),
        sa.Column('updated_by', sa.String(length=80), nullable=True),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.Column('updated_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('machine_id'),
        sa.UniqueConstraint('machine_code')
        )

    if 't_work_run' not in existing_tables:
        op.create_table('t_work_run',
        sa.Column('work_run_id', sa.Integer(), nullable=False),
        sa.Column('work_order_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('usable_qty', sa.Integer(), nullable=True),
        sa.Column('completion_remark', sa.String(length=500), nullable=True),
        sa.Column('wms_pick_reference', sa.String(length=100), nullable=True),
        sa.Column('status', sa.Enum('INPROGRESS', 'COMPLETED', name='workrunstatus'), nullable=False),
        sa.Column('current_phase_id', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.String(length=80), nullable=True),
        sa.Column('updated_by', sa.String(length=80), nullable=True),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.Column('updated_date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['current_phase_id'], ['t_work_phase.work_phase_id'], ),
        sa.ForeignKeyConstraint(['work_order_id'], ['t_work_order.work_order_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('work_run_id')
        )

    if 't_machine_maintenance' not in existing_tables:
        op.create_table('t_machine_maintenance',
        sa.Column('maintenance_id', sa.Integer(), nullable=False),
        sa.Column('machine_id', sa.Integer(), nullable=False),
        sa.Column('maintenance_date', sa.DateTime(), nullable=False),
        sa.Column('maintenance_type', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('fix_cost', sa.Float(), nullable=True),
        sa.Column('created_by', sa.String(length=80), nullable=True),
        sa.Column('updated_by', sa.String(length=80), nullable=True),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.Column('updated_date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['machine_id'], ['m_machine.machine_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('maintenance_id')
        )

    if 't_material_transaction' not in existing_tables:
        op.create_table('t_material_transaction',
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('material_list_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=24), nullable=False),
        sa.Column('related_document_code', sa.String(length=128), nullable=False),
        sa.Column('created_by', sa.String(length=80), nullable=True),
        sa.Column('updated_by', sa.String(length=80), nullable=True),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.Column('updated_date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['material_list_id'], ['t_material_list.material_list_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('transaction_id')
        )

    if 't_test_result_work_run' not in existing_tables:
        op.create_table('t_test_result_work_run',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('test_result_id', sa.Integer(), nullable=False),
        sa.Column('work_run_id', sa.Integer(), nullable=False),
        sa.Column('qty_from_run', sa.Integer(), nullable=False),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.Column('updated_date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['test_result_id'], ['t_test_result.test_result_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['work_run_id'], ['t_work_run.work_run_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )

    def get_columns(table):
        return {c['name'] for c in sa_inspect(conn).get_columns(table)}

    def get_fk_names(table):
        return {fk['name'] for fk in sa_inspect(conn).get_foreign_keys(table)}

    ml_cols = get_columns('t_material_list')
    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        if 'original_num' not in ml_cols:
            batch_op.add_column(sa.Column('original_num', sa.Integer(), nullable=False))
        if 'item_num' in ml_cols:
            batch_op.drop_column('item_num')

    qc_wo_cols = get_columns('t_qc_work_order')
    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        if 'qc_status' in qc_wo_cols:
            batch_op.drop_column('qc_status')

    tr_cols = get_columns('t_test_result')
    with op.batch_alter_table('t_test_result', schema=None) as batch_op:
        if 'claimed_qty' not in tr_cols:
            batch_op.add_column(sa.Column('claimed_qty', sa.Integer(), nullable=False))
        if 'session_status' not in tr_cols:
            batch_op.add_column(sa.Column('session_status', sa.Enum('INPROGRESS', 'COMPLETED', name='testsessionstatus'), nullable=False))
        batch_op.alter_column('qc_work_order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('overall_status',
               existing_type=mysql.ENUM('PASSED', 'FAILED'),
               nullable=True)
        tr_fks = get_fk_names('t_test_result')
        if 't_test_result_ibfk_1' in tr_fks:
            batch_op.drop_constraint(batch_op.f('t_test_result_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_qc_work_order', ['qc_work_order_id'], ['qc_work_order_id'], ondelete='SET NULL')

    wo_cols = get_columns('t_work_order')
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        if 'quantity' not in wo_cols:
            batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        if 'current_phase_id' in wo_cols:
            wo_fks = get_fk_names('t_work_order')
            if 't_work_order_ibfk_2' in wo_fks:
                batch_op.drop_constraint(batch_op.f('t_work_order_ibfk_2'), type_='foreignkey')
            batch_op.drop_column('current_phase_id')

    wp_cols = get_columns('t_work_phase')
    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        if 'work_run_id' not in wp_cols:
            batch_op.add_column(sa.Column('work_run_id', sa.Integer(), nullable=False))
        if 'work_order_id' in wp_cols:
            wp_fks = get_fk_names('t_work_phase')
            if 't_work_phase_ibfk_1' in wp_fks:
                batch_op.drop_constraint(batch_op.f('t_work_phase_ibfk_1'), type_='foreignkey')
            batch_op.create_foreign_key(None, 't_work_run', ['work_run_id'], ['work_run_id'], ondelete='CASCADE')
            batch_op.drop_column('work_order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_order_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_work_phase_ibfk_1'), 't_work_order', ['work_order_id'], ['work_order_id'])
        batch_op.drop_column('work_run_id')

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_phase_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('t_work_order_ibfk_2'), 't_work_phase', ['current_phase_id'], ['work_phase_id'])
        batch_op.drop_column('quantity')

    with op.batch_alter_table('t_test_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_test_result_ibfk_1'), 't_qc_work_order', ['qc_work_order_id'], ['qc_work_order_id'], ondelete='CASCADE')
        batch_op.alter_column('overall_status',
               existing_type=mysql.ENUM('PASSED', 'FAILED'),
               nullable=False)
        batch_op.alter_column('qc_work_order_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('session_status')
        batch_op.drop_column('claimed_qty')

    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qc_status', mysql.ENUM('PENDING', 'INPROGRESS', 'PASSED', 'FAILED'), nullable=False))

    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_num', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('original_num')

    op.drop_table('t_test_result_work_run')
    op.drop_table('t_material_transaction')
    op.drop_table('t_machine_maintenance')
    op.drop_table('t_work_run')
    op.drop_table('m_machine')
    # ### end Alembic commands ###
