"""vals_from_center

Revision ID: 085001b57cdc
Revises: h3c4d5e6f7g8
Create Date: 2026-04-02 10:56:13.774071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085001b57cdc'
down_revision = 'h3c4d5e6f7g8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('center_material_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('center_sales_item_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('center_sales_order_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        batch_op.drop_column('center_sales_order_id')

    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.drop_column('center_sales_item_id')

    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.drop_column('center_material_id')

    # ### end Alembic commands ###
