"""Make work_order.current_phase FK use_alter to avoid cycle

Revision ID: 149e5f6e90ff
Revises: cf5bd903f1f8
Create Date: 2026-02-17 13:22:15.436996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149e5f6e90ff'
down_revision = 'cf5bd903f1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_work_order_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key('fk_work_order_current_phase', 't_work_phase', ['current_phase_id'], ['work_phase_id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_work_order_current_phase', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_work_order_ibfk_1'), 't_work_phase', ['current_phase_id'], ['work_phase_id'])

    # ### end Alembic commands ###
