"""test_produce_indexes


Revision ID: 169d9128b9b1
Revises: c195bd62ffa2
Create Date: 2026-04-06 15:15:15.260954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169d9128b9b1'
down_revision = 'c195bd62ffa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.create_index('ix_sales_items_doc_entry_produce', ['doc_entry', 'produce'], unique=False)
        batch_op.create_index('ix_sales_items_doc_entry_test', ['doc_entry', 'test'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_items_doc_entry_test')
        batch_op.drop_index('ix_sales_items_doc_entry_produce')

    # ### end Alembic commands ###
