"""added_produce_test_bool_sales_item

Revision ID: 184234e7c6b2
Revises: 0031a9a756d1
Create Date: 2026-04-06 14:58:10.298245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184234e7c6b2'
down_revision = '0031a9a756d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produce', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('test', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.drop_column('test')
        batch_op.drop_column('produce')

    # ### end Alembic commands ###
