"""empty message

Revision ID: 1f11b2af8628
Revises: b810a2582e0e
Create Date: 2026-04-13 15:35:59.657764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f11b2af8628'
down_revision = 'b810a2582e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_line_num', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.drop_column('order_line_num')

    # ### end Alembic commands ###
