"""empty message

Revision ID: 291f545f4ad4
Revises: ded945a4cac9
Create Date: 2026-02-12 11:04:19.735878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '291f545f4ad4'
down_revision = 'ded945a4cac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_work_items')
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.alter_column('doc_entry',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.alter_column('doc_entry',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    op.create_table('t_work_items',
    sa.Column('work_item_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_phase_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sales_item_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['sales_item_id'], ['t_sales_items.sales_item_id'], name=op.f('t_work_items_ibfk_2')),
    sa.ForeignKeyConstraint(['work_phase_id'], ['t_work_phase.work_phase_id'], name=op.f('t_work_items_ibfk_1')),
    sa.PrimaryKeyConstraint('work_item_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
