"""empty message

Revision ID: 2cee524f05cc
Revises: f76fd54199a0
Create Date: 2026-02-13 11:03:28.211234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2cee524f05cc'
down_revision = 'f76fd54199a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_qc_work_order')
    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.alter_column('phase_status',
               existing_type=mysql.ENUM('Pending', 'InProgress', 'Completed', 'Cancelled'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.alter_column('phase_status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('Pending', 'InProgress', 'Completed', 'Cancelled'),
               existing_nullable=False)

    op.create_table('t_qc_work_order',
    sa.Column('qc_work_order_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('qc_work_order_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
