"""added_mat_item_group

Revision ID: 2f72e1c6942c
Revises: 7be5591d6f96
Create Date: 2026-04-07 10:01:06.927751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f72e1c6942c'
down_revision = '7be5591d6f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_group', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.drop_column('item_group')

    # ### end Alembic commands ###
