"""empty message

Revision ID: 3279f5f400e9
Revises: e4c636d3a610
Create Date: 2026-04-16 15:35:59.501912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3279f5f400e9'
down_revision = 'e4c636d3a610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_picking_item_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picking_request_item_id', sa.Integer(), nullable=False),
    sa.Column('delta_qty', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('MISCOUNT', 'SPILLAGE', 'CORRECTION', 'OTHER', name='pickingitemadjustmentreason'), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['picking_request_item_id'], ['t_picking_request_item.picking_request_item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('t_picking_item_adjustment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_picking_item_adjustment_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('t_work_run_required_item', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_run_required_item', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('t_picking_item_adjustment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_picking_item_adjustment_branch_id'))

    op.drop_table('t_picking_item_adjustment')
    # ### end Alembic commands ###
