"""empty message

Revision ID: 33f00a3bd304
Revises: dd328a3cf3c2
Create Date: 2026-02-09 10:12:49.336210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f00a3bd304'
down_revision = 'dd328a3cf3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('t_token_list', schema=None) as batch_op:
        batch_op.drop_index('t_token_list_m_user_FK')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_token_list', schema=None) as batch_op:
        batch_op.create_index('t_token_list_m_user_FK', ['user_id'], unique=False)

    with op.batch_alter_table('m_user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
