"""empty message

Revision ID: 3756109e58b9
Revises: a2f93d4c7bfc
Create Date: 2026-03-05 12:34:55.215247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3756109e58b9'
down_revision = 'a2f93d4c7bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
