"""empty message

Revision ID: 377a76079dcb
Revises: 60def7f542a6
Create Date: 2026-02-11 14:54:27.788883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377a76079dcb'
down_revision = '60def7f542a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 't_work_order', ['work_order_id'], ['work_order_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('work_order_id')

    # ### end Alembic commands ###
