"""work_order_m-1_sales_item

Revision ID: 3a8336164dd8
Revises: cc1a34d613b1
Create Date: 2026-03-11 16:57:20.934338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a8336164dd8'
down_revision = 'cc1a34d613b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.alter_column('original_num',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('ORIGINAL', 'REWORK', name='workordertype'), nullable=False))
        batch_op.add_column(sa.Column('source_qc_work_order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wms_pick_reference', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 't_qc_work_order', ['source_qc_work_order_id'], ['qc_work_order_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('wms_pick_reference')
        batch_op.drop_column('source_qc_work_order_id')
        batch_op.drop_column('type')

    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.alter_column('original_num',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
