"""empty message

Revision ID: 3b0e03b732d4
Revises: cecb53e907f1
Create Date: 2026-02-24 09:17:47.937665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from migrations.utils import column_exists

# revision identifiers, used by Alembic.
revision = '3b0e03b732d4'
down_revision = 'cecb53e907f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        if not column_exists('t_item_component', 'work_order_id'):
            batch_op.add_column(sa.Column('work_order_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('t_item_component_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_work_order', ['work_order_id'], ['work_order_id'], ondelete='CASCADE')
        if column_exists('t_item_component', 'sale_item_id'):
            batch_op.drop_column('sale_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_item_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_item_component_ibfk_1'), 't_sales_items', ['sale_item_id'], ['sales_item_id'], ondelete='CASCADE')
        batch_op.drop_column('work_order_id')

    # ### end Alembic commands ###
