"""Added_Transactions

Revision ID: 3c4afddf9fbb
Revises: 5f87286c3589
Create Date: 2026-03-09 12:08:59.901128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4afddf9fbb'
down_revision = '5f87286c3589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_component_option_type',
    sa.Column('component_option_type_id', sa.Integer(), nullable=False),
    sa.Column('component_option_type_name', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('component_option_type_id')
    )
    op.create_table('t_component_spec_type',
    sa.Column('component_spec_type_id', sa.Integer(), nullable=False),
    sa.Column('component_spec_type_name', sa.String(length=255), nullable=False),
    sa.Column('spec_type', sa.Enum('boolean', 'decimal', 'text'), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('component_spec_type_id')
    )
    op.create_table('t_component_option',
    sa.Column('component_option_id', sa.Integer(), nullable=False),
    sa.Column('component_option_type_id', sa.Integer(), nullable=False),
    sa.Column('item_component_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_option_type_id'], ['t_component_option_type.component_option_type_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_component_id'], ['t_item_component.item_component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_option_id')
    )
    op.create_table('t_component_spec',
    sa.Column('component_spec_id', sa.Integer(), nullable=False),
    sa.Column('item_component_id', sa.Integer(), nullable=False),
    sa.Column('component_spec_type_id', sa.Integer(), nullable=False),
    sa.Column('end_side', sa.Enum('top', 'bottom'), nullable=True),
    sa.Column('bool_value', sa.Boolean(), nullable=True),
    sa.Column('decimal_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('text_value', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_spec_type_id'], ['t_component_spec_type.component_spec_type_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_component_id'], ['t_item_component.item_component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_spec_id'),
    sa.UniqueConstraint('item_component_id', 'component_spec_type_id', 'end_side', name='uq_item_component_spec')
    )
    op.create_table('t_material_transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('material_list_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('related_document_code', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_list_id'], ['t_material_list.material_list_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_material_transaction')
    op.drop_table('t_component_spec')
    op.drop_table('t_component_option')
    op.drop_table('t_component_spec_type')
    op.drop_table('t_component_option_type')
    # ### end Alembic commands ###
