"""empty message

Revision ID: 420e04010f30
Revises: 7125048ba02e
Create Date: 2026-02-11 10:07:22.347122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420e04010f30'
down_revision = '7125048ba02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
