"""picking

Revision ID: 4c9e64f3b855
Revises: c5d6e7f8a9b0
Create Date: 2026-03-21 13:30:23.917698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9e64f3b855'
down_revision = 'c5d6e7f8a9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_picking_request',
    sa.Column('picking_request_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.Enum('WORK_RUN', 'TEST_RESULT', name='pickingrequesttype'), nullable=False),
    sa.Column('work_run_id', sa.Integer(), nullable=True),
    sa.Column('test_result_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'SUCCESS', 'FAILED', name='pickingrequeststatus'), nullable=False),
    sa.Column('wms_reference', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_result_id'], ['t_test_result.test_result_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_run_id'], ['t_work_run.work_run_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('picking_request_id')
    )
    op.create_table('t_picking_request_item',
    sa.Column('picking_request_item_id', sa.Integer(), nullable=False),
    sa.Column('picking_request_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['picking_request_id'], ['t_picking_request.picking_request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('picking_request_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_picking_request_item')
    op.drop_table('t_picking_request')
    # ### end Alembic commands ###
