"""fix-table-qc 

Revision ID: 4dff5baf3a93
Revises: 8709ab6f7c1d
Create Date: 2026-02-25 14:05:33.466177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dff5baf3a93'
down_revision = '8709ab6f7c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 't_sales_order', ['doc_entry'], ['doc_entry'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
