"""sales_item_more_prop

Revision ID: 4e2ad0dd554f
Revises: d25e6d663da0
Create Date: 2026-03-23 14:36:31.325466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2ad0dd554f'
down_revision = 'd25e6d663da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'PASSED', name='qcworkorderstatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
