"""empty message

Revision ID: 4f0fd9f80339
Revises: 5eca83c78e8a
Create Date: 2026-02-16 11:48:06.794207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f0fd9f80339'
down_revision = '5eca83c78e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_work_items')
    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['doc_num'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    op.create_table('t_work_items',
    sa.Column('work_item_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_phase_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sales_item_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['sales_item_id'], ['t_sales_items.sales_item_id'], name='t_work_items_ibfk_2'),
    sa.ForeignKeyConstraint(['work_phase_id'], ['t_work_phase.work_phase_id'], name='t_work_items_ibfk_1'),
    sa.PrimaryKeyConstraint('work_item_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
