"""add-pm-machine

Revision ID: 50b110ce2167
Revises: 1da9edfa99dc
Create Date: 2026-03-11 10:06:29.204745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50b110ce2167'
down_revision = '1da9edfa99dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_machine_maintenance',
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_date', sa.DateTime(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['m_machine.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.alter_column('original_num',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.alter_column('original_num',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.drop_table('t_machine_maintenance')
    # ### end Alembic commands ###
