"""enforce 1to1 qc_work_order

Revision ID: 5445fbfb0f48
Revises: d3e5fc3abbc2
Create Date: 2026-02-23 15:51:03.819041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5445fbfb0f48'
down_revision = 'd3e5fc3abbc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['work_order_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
