"""sales_order_status

Revision ID: 551c6af34be8
Revises: 4e2ad0dd554f
Create Date: 2026-03-23 16:11:52.547592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551c6af34be8'
down_revision = '4e2ad0dd554f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('INPROGRESS', 'COMPLETED', name='salesorderstatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
