"""add useful_life_years and working_hours_per_day to machine

Revision ID: 56932c5cafc4
Revises: 05745cc2805d
Create Date: 2026-04-22 09:09:22.861855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56932c5cafc4'
down_revision = '05745cc2805d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('useful_life_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('working_hours_per_day', sa.Integer(), nullable=True))
        batch_op.alter_column('purchase_price',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.alter_column('purchase_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('working_hours_per_day')
        batch_op.drop_column('useful_life_years')

    # ### end Alembic commands ###
