"""develop_test

Revision ID: 596848cb2e8c
Revises: eb740f07e2e3
Create Date: 2026-02-27 10:09:17.829987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '596848cb2e8c'
down_revision = 'eb740f07e2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        batch_op.drop_column('sale_item_id')

    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_item_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('qc_status', sa.Enum('PENDING', 'INPROGRESS', 'PASSED', 'FAILED', name='qcworkorderstatus'), nullable=False))
        batch_op.add_column(sa.Column('qc_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('qc_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('remark', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key(None, 't_sales_items', ['sales_item_id'], ['sales_item_id'], ondelete='CASCADE')

    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'INPROGRESS', 'COMPLETED', name='salesitemstatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('remark')
        batch_op.drop_column('qc_by')
        batch_op.drop_column('qc_date')
        batch_op.drop_column('qc_status')
        batch_op.drop_column('sales_item_id')

    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_item_id', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
