"""description of changes

Revision ID: 5a62d089e081
Revises: 
Create Date: 2026-02-04 10:39:59.682752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a62d089e081'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m_role')
    with op.batch_alter_table('m_permission', schema=None) as batch_op:
        batch_op.drop_index('permission_code')

    op.drop_table('m_permission')
    op.drop_table('m_role_permission')
    with op.batch_alter_table('m_user', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('m_user_m_role_FK', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_user', schema=None) as batch_op:
        batch_op.create_foreign_key('m_user_m_role_FK', 'm_role', ['role_id'], ['role_id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.alter_column('role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.create_table('m_role_permission',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['m_permission.permission_id'], name='m_role_permission_ibfk_2'),
    sa.ForeignKeyConstraint(['role_id'], ['m_role.role_id'], name='m_role_permission_ibfk_1'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('m_permission',
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('permission_code', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('permission_group', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('m_permission', schema=None) as batch_op:
        batch_op.create_index('permission_code', ['permission_code'], unique=True)

    op.create_table('m_role',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
