"""added_item_group

Revision ID: 5ab5bc9017aa
Revises: 169d9128b9b1
Create Date: 2026-04-07 09:38:30.716348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab5bc9017aa'
down_revision = '169d9128b9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_group', sa.Float(), nullable=False))

    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_group', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.drop_column('item_group')

    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.drop_column('item_group')

    # ### end Alembic commands ###
