"""added sales order

Revision ID: 5eca83c78e8a
Revises: 73dcc3dabe83
Create Date: 2026-02-14 22:44:59.307902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5eca83c78e8a'
down_revision = '73dcc3dabe83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.alter_column('doc_entry',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 't_sales_order', ['doc_entry'], ['doc_entry'])

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.alter_column('doc_entry',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 't_sales_order', ['doc_entry'], ['doc_entry'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('doc_entry',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('doc_entry',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
