"""empty message

Revision ID: 60def7f542a6
Revises: 6c5ef01bb4e2
Create Date: 2026-02-11 11:19:03.863395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60def7f542a6'
down_revision = '6c5ef01bb4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_phase_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 't_work_phase', ['current_phase_id'], ['work_phase_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_phase_id')

    # ### end Alembic commands ###
