"""empty message

Revision ID: 6233f31d35a2
Revises: e974483f68a5
Create Date: 2026-02-17 15:23:08.521936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6233f31d35a2'
down_revision = 'e974483f68a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_work_assignment_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_work_phase', ['work_phase_id'], ['work_phase_id'], ondelete='CASCADE')

    with op.batch_alter_table('t_work_phase_break', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_work_phase_break_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_work_phase', ['work_phase_id'], ['work_phase_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase_break', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_work_phase_break_ibfk_1'), 't_work_phase', ['work_phase_id'], ['work_phase_id'])

    with op.batch_alter_table('t_work_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_work_assignment_ibfk_3'), 't_work_phase', ['work_phase_id'], ['work_phase_id'])

    # ### end Alembic commands ###
