"""add section_key to component_template_section_data

Revision ID: 6b505740d3f5
Revises: cd92aaa0d0d6
Create Date: 2026-03-20 11:33:06.348784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b505740d3f5'
down_revision = 'cd92aaa0d0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_component_template_section_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_key', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_component_template_section_data', schema=None) as batch_op:
        batch_op.drop_column('section_key')

    # ### end Alembic commands ###
