"""empty message

Revision ID: 6c5ef01bb4e2
Revises: 420e04010f30
Create Date: 2026-02-11 10:47:13.974563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5ef01bb4e2'
down_revision = '420e04010f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('phase_status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.drop_column('phase_status')
        batch_op.drop_column('phase_name')

    # ### end Alembic commands ###
