"""empty message

Revision ID: 7125048ba02e
Revises: ffff117e3f6b
Create Date: 2026-02-11 09:51:13.554776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7125048ba02e'
down_revision = 'ffff117e3f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.drop_column('salary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
