"""change docs type

Revision ID: 73dcc3dabe83
Revises: 2cee524f05cc
Create Date: 2026-02-14 22:28:15.412273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73dcc3dabe83'
down_revision = '2cee524f05cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_entry', sa.Integer(), nullable=False))
        batch_op.alter_column('doc_num',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.alter_column('doc_num',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('doc_entry',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.alter_column('doc_entry',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('doc_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.alter_column('doc_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('doc_entry')

    # ### end Alembic commands ###
