"""qc_work_order_CRUD

Revision ID: 75b0e1e0822d
Revises: 8932afa6f8b2
Create Date: 2026-02-23 11:39:49.925415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b0e1e0822d'
down_revision = '8932afa6f8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_order_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('qc_status', sa.Enum('PENDING', 'INPROGRESS', 'PASSED', 'FAILED', name='qcworkorderstatus'), nullable=False))
        batch_op.add_column(sa.Column('qc_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('qc_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('remark', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key(None, 't_work_order', ['work_order_id'], ['work_order_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('remark')
        batch_op.drop_column('qc_by')
        batch_op.drop_column('qc_date')
        batch_op.drop_column('qc_status')
        batch_op.drop_column('work_order_id')

    # ### end Alembic commands ###
