"""rename item_num to quantity in t_sales_item

Revision ID: 799e62318802
Revises: a1b2c3d4e5f7
Create Date: 2026-04-10 01:57:50.068228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '799e62318802'
down_revision = 'a1b2c3d4e5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.alter_column('item_num', new_column_name='quantity', existing_type=sa.Integer(), nullable=False)
        batch_op.add_column(sa.Column('order_line_num', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_code', sa.String(28), nullable=True))

    with op.batch_alter_table('t_work_run_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_run_assignment_branch_id'))
        batch_op.create_index(batch_op.f('ix_t_work_run_assignment_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('t_work_run_break', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_run_break_branch_id'))
        batch_op.create_index(batch_op.f('ix_t_work_run_break_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('t_work_run_machine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_run_machine_branch_id'))
        batch_op.create_index(batch_op.f('ix_t_work_run_machine_branch_id'), ['branch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_run_machine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_machine_branch_id'))
        batch_op.create_index(batch_op.f('ix_work_run_machine_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('t_work_run_break', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_break_branch_id'))
        batch_op.create_index(batch_op.f('ix_work_run_break_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('t_work_run_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_assignment_branch_id'))
        batch_op.create_index(batch_op.f('ix_work_run_assignment_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.drop_column('unit_code')
        batch_op.drop_column('order_line_num')
        batch_op.alter_column('quantity', new_column_name='item_num', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###
