"""delete_mat_item_group

Revision ID: 7be5591d6f96
Revises: 5ab5bc9017aa
Create Date: 2026-04-07 10:00:38.636425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7be5591d6f96'
down_revision = '5ab5bc9017aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.drop_column('item_group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_group', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
