"""make break_end nullable

Revision ID: 7f83ccb10f3d
Revises: 4f0fd9f80339
Create Date: 2026-02-16 14:29:36.511588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f83ccb10f3d'
down_revision = '4f0fd9f80339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase_break', schema=None) as batch_op:
        batch_op.alter_column('break_end',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase_break', schema=None) as batch_op:
        batch_op.alter_column('break_end',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
