"""remove performed_by  to machine_maintenance

Revision ID: 82519a919bef
Revises: 2017b782c635
Create Date: 2026-03-11 11:10:30.826640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82519a919bef'
down_revision = '2017b782c635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_machine_maintenance', schema=None) as batch_op:
        batch_op.drop_column('performed_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_machine_maintenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performed_by', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
