"""empty message

Revision ID: 827e0000324e
Revises: 
Create Date: 2026-02-19 09:30:04.962603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '827e0000324e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('ว่างงาน', 'ทํางานอยู่', 'หยุดงาน', 'ลางาน'),
               type_=sa.Enum('UNEMPLOYED', 'ACTIVE', 'ON_LEAVE', 'SUSPENDED', name='employeestatus'),
               existing_nullable=False)

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('พร้อม', 'กําลังดําเนินการ', 'เสร็จสิ้น'),
               type_=sa.Enum('READY', 'IN_PROGRESS', 'COMPLETED', name='workorderstatus'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_work_order_current_phase'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_work_phase', ['current_phase_id'], ['work_phase_id'])

    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.alter_column('phase_status',
               existing_type=mysql.ENUM('รอดําเนินการ', 'กําลังดําเนินการ', 'หยุดชั่วคราว', 'เสร็จสิ้น'),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', name='phasestatus'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('t_work_phase_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_work_order', ['work_order_id'], ['work_order_id'])

    with op.batch_alter_table('t_work_phase_break', schema=None) as batch_op:
        batch_op.alter_column('break_type',
               existing_type=mysql.ENUM('พักกลางวัน', 'พักเบรค', 'อื่นๆ'),
               type_=sa.Enum('LUNCHBREAK', 'RESTBREAK', 'OTHER', name='breaktype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase_break', schema=None) as batch_op:
        batch_op.alter_column('break_type',
               existing_type=sa.Enum('LUNCHBREAK', 'RESTBREAK', 'OTHER', name='breaktype'),
               type_=mysql.ENUM('พักกลางวัน', 'พักเบรค', 'อื่นๆ'),
               existing_nullable=False)

    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_work_phase_ibfk_1'), 't_work_order', ['work_order_id'], ['work_order_id'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.alter_column('phase_status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', name='phasestatus'),
               type_=mysql.ENUM('รอดําเนินการ', 'กําลังดําเนินการ', 'หยุดชั่วคราว', 'เสร็จสิ้น'),
               existing_nullable=False)

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_work_order_current_phase'), 't_work_phase', ['current_phase_id'], ['work_phase_id'], ondelete='SET NULL')
        batch_op.alter_column('status',
               existing_type=sa.Enum('READY', 'IN_PROGRESS', 'COMPLETED', name='workorderstatus'),
               type_=mysql.ENUM('พร้อม', 'กําลังดําเนินการ', 'เสร็จสิ้น'),
               existing_nullable=False)

    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('UNEMPLOYED', 'ACTIVE', 'ON_LEAVE', 'SUSPENDED', name='employeestatus'),
               type_=mysql.ENUM('ว่างงาน', 'ทํางานอยู่', 'หยุดงาน', 'ลางาน'),
               existing_nullable=False)

    # ### end Alembic commands ###
