"""--help

Revision ID: 8709ab6f7c1d
Revises: da8ed1cb0fb6
Create Date: 2026-02-25 11:43:02.765796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8709ab6f7c1d'
down_revision = 'da8ed1cb0fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_qc_certification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certification_number', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('standard_reference', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('test_method', sa.String(length=255), nullable=True))
        batch_op.drop_column('certification_name')

    with op.batch_alter_table('t_qc_check_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qc_certification_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('item_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 't_qc_certification', ['qc_certification_id'], ['qc_certification_id'], ondelete='CASCADE')

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 't_sales_order', ['doc_entry'], ['doc_entry'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('t_qc_check_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('description')
        batch_op.drop_column('item_no')
        batch_op.drop_column('qc_certification_id')

    with op.batch_alter_table('t_qc_certification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certification_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('test_method')
        batch_op.drop_column('standard_reference')
        batch_op.drop_column('certification_number')

    # ### end Alembic commands ###
