"""document_code_geneation

Revision ID: 884e940eedea
Revises: e677c81beaed
Create Date: 2026-03-23 09:36:28.077346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884e940eedea'
down_revision = 'e677c81beaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_document_code_list',
    sa.Column('document_code_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gen_number_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('document_code_id'),
    sa.UniqueConstraint('gen_number_type')
    )
    op.create_table('m_gen_number_config',
    sa.Column('gen_number_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gen_number_type', sa.String(length=50), nullable=False),
    sa.Column('gen_number_prefix', sa.String(length=20), nullable=True),
    sa.Column('gen_number_format', sa.String(length=100), nullable=False),
    sa.Column('gen_number_current', sa.Integer(), nullable=False),
    sa.Column('year_buddhist', sa.Boolean(), nullable=True),
    sa.Column('document_code_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_code_id'], ['m_document_code_list.document_code_id'], ),
    sa.PrimaryKeyConstraint('gen_number_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m_gen_number_config')
    op.drop_table('m_document_code_list')
    # ### end Alembic commands ###
