"""empty message

Revision ID: 8932afa6f8b2
Revises: fe21e2325aca
Create Date: 2026-02-23 10:07:21.390887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from migrations.utils import column_exists

# revision identifiers, used by Alembic.
revision = '8932afa6f8b2'
down_revision = 'fe21e2325aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('UNEMPLOYED', 'ACTIVE', 'ON_LEAVE', 'SUSPENDED'),
               type_=sa.Enum('UNEMPLOYED', 'ACTIVE', 'ONLEAVE', 'SUSPENDED', name='employeestatus'),
               existing_nullable=False)

    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        if not column_exists('t_sales_order', 'card_code'):
            batch_op.add_column(sa.Column('card_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('card_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('slp_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('slp_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('bpl_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('bpl_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('group_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('group_name', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        batch_op.drop_column('group_name')
        batch_op.drop_column('group_code')
        batch_op.drop_column('bpl_name')
        batch_op.drop_column('bpl_code')
        batch_op.drop_column('slp_name')
        batch_op.drop_column('slp_code')
        batch_op.drop_column('card_name')
        batch_op.drop_column('card_code')

    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('UNEMPLOYED', 'ACTIVE', 'ONLEAVE', 'SUSPENDED', name='employeestatus'),
               type_=mysql.ENUM('UNEMPLOYED', 'ACTIVE', 'ON_LEAVE', 'SUSPENDED'),
               existing_nullable=False)

    # ### end Alembic commands ###
