"""rm-auth-sig

Revision ID: 8e529a9295d1
Revises: 4dff5baf3a93
Create Date: 2026-02-25 14:38:24.365654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e529a9295d1'
down_revision = '4dff5baf3a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_qc_certification', schema=None) as batch_op:
        batch_op.drop_column('authorize_signature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_qc_certification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorize_signature', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
