"""empty message

Revision ID: 99796086cdb8
Revises: 377a76079dcb
Create Date: 2026-02-12 10:30:59.313833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99796086cdb8'
down_revision = '377a76079dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_work_items')
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_sales_items_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('work_order_id')

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_entry', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_column('doc_entry')

    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_order_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('t_sales_items_ibfk_1'), 't_work_order', ['work_order_id'], ['work_order_id'])

    op.create_table('t_work_items',
    sa.Column('work_item_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_phase_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sales_item_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['sales_item_id'], ['t_sales_items.sales_item_id'], name=op.f('t_work_items_ibfk_2')),
    sa.ForeignKeyConstraint(['work_phase_id'], ['t_work_phase.work_phase_id'], name=op.f('t_work_items_ibfk_1')),
    sa.PrimaryKeyConstraint('work_item_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
