"""added work runs

Revision ID: 9a7ea6cd30c6
Revises: 3a8336164dd8
Create Date: 2026-03-12 21:39:16.986728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a7ea6cd30c6'
down_revision = '3a8336164dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_work_run',
    sa.Column('work_run_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('wms_pick_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('INPROGRESS', 'COMPLETED', name='workrunstatus'), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['t_work_order.work_order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_run_id')
    )
    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.drop_column('qc_status')

    with op.batch_alter_table('t_test_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_run_id', sa.Integer(), nullable=False))
        batch_op.alter_column('qc_work_order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('t_test_result_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_qc_work_order', ['qc_work_order_id'], ['qc_work_order_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 't_work_run', ['work_run_id'], ['work_run_id'], ondelete='CASCADE')

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_constraint('t_work_order_ibfk_4', type_='foreignkey')
        batch_op.drop_column('type')
        batch_op.drop_column('wms_pick_reference')
        batch_op.drop_column('source_qc_work_order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_qc_work_order_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wms_pick_reference', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('type', mysql.ENUM('ORIGINAL', 'REWORK'), nullable=False))
        batch_op.create_foreign_key('t_work_order_ibfk_4', 't_qc_work_order', ['source_qc_work_order_id'], ['qc_work_order_id'])

    with op.batch_alter_table('t_test_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_test_result_ibfk_1', 't_qc_work_order', ['qc_work_order_id'], ['qc_work_order_id'], ondelete='CASCADE')
        batch_op.alter_column('qc_work_order_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('work_run_id')

    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qc_status', mysql.ENUM('PENDING', 'INPROGRESS', 'PASSED', 'FAILED'), nullable=False))

    op.drop_table('t_work_run')
    # ### end Alembic commands ###
