"""empty message

Revision ID: a0b651b3e0f0
Revises: bcb213de9078
Create Date: 2026-03-24 10:34:02.998061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b651b3e0f0'
down_revision = 'bcb213de9078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_branch', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
