"""empty message

Revision ID: a236c5dd3c0e
Revises: 596848cb2e8c
Create Date: 2026-03-05 11:58:24.684793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a236c5dd3c0e'
down_revision = '596848cb2e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_component_material_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_component_material_usage', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
