"""Add composite unique constraint to machine

Revision ID: a26ea1d50108
Revises: e3fd6b598ab6
Create Date: 2026-03-19 16:04:41.190715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26ea1d50108'
down_revision = 'e3fd6b598ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('machine_code'))
        batch_op.create_unique_constraint('uq_branch_machine_code', ['branch_id', 'machine_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.drop_constraint('uq_branch_machine_code', type_='unique')
        batch_op.create_index(batch_op.f('machine_code'), ['machine_code'], unique=True)

    # ### end Alembic commands ###
