"""empty message

Revision ID: a2f93d4c7bfc
Revises: a236c5dd3c0e
Create Date: 2026-03-05 12:18:47.920406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f93d4c7bfc'
down_revision = 'a236c5dd3c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        batch_op.drop_column('remark')

    # ### end Alembic commands ###
