"""empty message

Revision ID: a7c501b99c70
Revises: daf99f430b4c
Create Date: 2026-03-18 11:51:47.020546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7c501b99c70'
down_revision = 'daf99f430b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_component_template_section_data',
    sa.Column('section_data_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('item_component_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_component_id'], ['t_item_component.item_component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_data_id')
    )
    op.drop_table('t_component_template_section_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_component_template_section_data',
    sa.Column('section_data_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('data', mysql.JSON(), nullable=False),
    sa.Column('item_component_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['item_component_id'], ['t_item_component.item_component_id'], name=op.f('t_component_template_section_data_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_data_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('m_component_template_section_data')
    # ### end Alembic commands ###
