"""Add is_active to m_branch for soft delete

Revision ID: abc5b5fe52d1
Revises: a26ea1d50108
Create Date: 2026-03-20 08:51:23.502399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc5b5fe52d1'
down_revision = 'a26ea1d50108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_branch', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
