"""init

Revision ID: adbcba965679
Revises: 
Create Date: 2026-05-19 10:50:26.832541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbcba965679'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_branch',
    sa.Column('branch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_code', sa.String(length=20), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('branch_id'),
    sa.UniqueConstraint('branch_code')
    )
    op.create_table('m_component_template',
    sa.Column('component_template_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('component_template_id')
    )
    op.create_table('m_document_code_list',
    sa.Column('document_code_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gen_number_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('document_code_id'),
    sa.UniqueConstraint('gen_number_type')
    )
    op.create_table('m_holiday',
    sa.Column('holiday_id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('holiday_id'),
    sa.UniqueConstraint('holiday_date')
    )
    op.create_table('m_machine_type',
    sa.Column('machine_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('type_description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('machine_type_id')
    )
    op.create_table('m_module',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=False),
    sa.Column('module_code', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('module_id'),
    sa.UniqueConstraint('module_code')
    )
    op.create_table('m_operation_cost_monthly',
    sa.Column('operation_cost_monthly_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_cost_date', sa.Date(), nullable=False),
    sa.Column('depreciation_building_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('depreciation_building_period', sa.Integer(), nullable=False),
    sa.Column('depreciation_util_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('depreciation_util_period', sa.Integer(), nullable=False),
    sa.Column('office_rent_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('office_supplies_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('water_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('electricity_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('utility_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('operation_cost_monthly_id')
    )
    op.create_table('m_phase_template',
    sa.Column('phase_template_id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('phase_template_id')
    )
    op.create_table('m_role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=80), nullable=False),
    sa.Column('role_name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('active_flag', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('m_shift',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('work_days', sa.String(length=40), nullable=False),
    sa.Column('ot_multiplier', sa.Float(), nullable=False),
    sa.Column('weekend_multiplier', sa.Float(), nullable=False),
    sa.Column('holiday_multiplier', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_table('t_token_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jwt_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jwt_id')
    )
    op.create_table('m_gen_number_config',
    sa.Column('gen_number_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gen_number_type', sa.String(length=50), nullable=False),
    sa.Column('gen_number_prefix', sa.String(length=20), nullable=True),
    sa.Column('gen_number_format', sa.String(length=100), nullable=False),
    sa.Column('gen_number_current', sa.Integer(), nullable=False),
    sa.Column('year_buddhist', sa.Boolean(), nullable=True),
    sa.Column('document_code_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_code_id'], ['m_document_code_list.document_code_id'], ),
    sa.PrimaryKeyConstraint('gen_number_id')
    )
    op.create_table('m_machine',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('machine_code', sa.String(length=50), nullable=False),
    sa.Column('machine_name', sa.String(length=255), nullable=False),
    sa.Column('machine_description', sa.String(length=500), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('useful_life_years', sa.Integer(), nullable=True),
    sa.Column('working_hours_per_day', sa.Integer(), nullable=True),
    sa.Column('remaining_maintenance_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'DOWN', 'IDLE', 'OFFLINE', name='machinestatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_second_hand', sa.Boolean(), nullable=False),
    sa.Column('accumulated_hours', sa.Float(), nullable=True),
    sa.Column('machine_type_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['machine_type_id'], ['m_machine_type.machine_type_id'], ),
    sa.PrimaryKeyConstraint('machine_id'),
    sa.UniqueConstraint('branch_id', 'machine_code', name='uq_branch_machine_code')
    )
    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_m_machine_branch_id'), ['branch_id'], unique=False)

    op.create_table('m_permission',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('permission_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['m_module.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('module_id', 'method', name='uq_permission_module_method')
    )
    op.create_table('m_phase_template_item',
    sa.Column('phase_template_item_id', sa.Integer(), nullable=False),
    sa.Column('phase_template_id', sa.Integer(), nullable=False),
    sa.Column('phase_name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('machine_type_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_type_id'], ['m_machine_type.machine_type_id'], ),
    sa.ForeignKeyConstraint(['phase_template_id'], ['m_phase_template.phase_template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phase_template_item_id')
    )
    op.create_table('m_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['m_role.role_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('t_sales_order',
    sa.Column('doc_entry', sa.Integer(), nullable=False),
    sa.Column('center_sales_order_id', sa.Integer(), nullable=True),
    sa.Column('doc_num', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INPROGRESS', 'COMPLETED', name='salesorderstatus'), nullable=False),
    sa.Column('card_code', sa.String(length=20), nullable=False),
    sa.Column('card_name', sa.String(length=200), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('slp_code', sa.String(length=20), nullable=False),
    sa.Column('slp_name', sa.String(length=200), nullable=False),
    sa.Column('bpl_code', sa.String(length=20), nullable=False),
    sa.Column('bpl_name', sa.String(length=200), nullable=False),
    sa.Column('group_code', sa.String(length=20), nullable=False),
    sa.Column('group_name', sa.String(length=200), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.PrimaryKeyConstraint('doc_entry'),
    sa.UniqueConstraint('doc_num')
    )
    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_sales_order_branch_id'), ['branch_id'], unique=False)

    op.create_table('m_employee',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_first_name', sa.String(length=100), nullable=False),
    sa.Column('employee_last_name', sa.String(length=100), nullable=False),
    sa.Column('citizen_id', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('UNEMPLOYED', 'ACTIVE', 'ONLEAVE', 'SUSPENDED', name='employeestatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('day_rate', sa.Float(), nullable=False),
    sa.Column('ot_hourly_rate', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['m_user.user_id'], ),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('citizen_id')
    )
    op.create_table('m_role_permission',
    sa.Column('role_permission_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('active_flag', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['m_permission.permission_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['m_role.role_id'], ),
    sa.PrimaryKeyConstraint('role_permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('map_user_branch',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['m_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'branch_id')
    )
    op.create_table('t_machine_maintenance',
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_date', sa.DateTime(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('fix_cost', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['m_machine.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    with op.batch_alter_table('t_machine_maintenance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_machine_maintenance_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_picking_request',
    sa.Column('picking_request_id', sa.Integer(), nullable=False),
    sa.Column('picking_request_code', sa.String(length=100), nullable=True),
    sa.Column('doc_entry', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'SUCCESS', 'FAILED', name='pickingrequeststatus'), nullable=False),
    sa.Column('wms_reference', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('is_reallocation', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['doc_entry'], ['t_sales_order.doc_entry'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('picking_request_id')
    )
    with op.batch_alter_table('t_picking_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_picking_request_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_qc_certification',
    sa.Column('qc_certification_id', sa.Integer(), nullable=False),
    sa.Column('certification_number', sa.String(length=255), nullable=False),
    sa.Column('certification_date', sa.DateTime(), nullable=False),
    sa.Column('standard_reference', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('test_method', sa.String(length=255), nullable=True),
    sa.Column('certification_status', sa.Enum('PASSED', 'FAILED', name='certificationstatus'), nullable=False),
    sa.Column('doc_entry', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_entry'], ['t_sales_order.doc_entry'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qc_certification_id')
    )
    op.create_table('t_sales_items',
    sa.Column('sales_item_id', sa.Integer(), nullable=False),
    sa.Column('center_sales_item_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INPROGRESS', 'COMPLETED', name='salesitemstatus'), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_line_num', sa.Integer(), nullable=True),
    sa.Column('unit_name', sa.String(length=28), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_description', sa.String(length=500), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('doc_num', sa.Integer(), nullable=False),
    sa.Column('doc_entry', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('produce', sa.Boolean(), nullable=False),
    sa.Column('test', sa.Boolean(), nullable=False),
    sa.Column('item_group', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['doc_entry'], ['t_sales_order.doc_entry'], ),
    sa.PrimaryKeyConstraint('sales_item_id')
    )
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.create_index('ix_sales_items_doc_entry_produce', ['doc_entry', 'produce'], unique=False)
        batch_op.create_index('ix_sales_items_doc_entry_test', ['doc_entry', 'test'], unique=False)
        batch_op.create_index(batch_op.f('ix_t_sales_items_branch_id'), ['branch_id'], unique=False)

    op.create_table('m_employee_shift',
    sa.Column('employee_shift_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('work_days', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['m_employee.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_shift_id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('t_employee_salary_history',
    sa.Column('salary_history_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('old_base_salary', sa.Float(), nullable=False),
    sa.Column('new_base_salary', sa.Float(), nullable=False),
    sa.Column('old_day_rate', sa.Float(), nullable=False),
    sa.Column('new_day_rate', sa.Float(), nullable=False),
    sa.Column('old_ot_hourly_rate', sa.Float(), nullable=False),
    sa.Column('new_ot_hourly_rate', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['m_employee.employee_id'], ),
    sa.PrimaryKeyConstraint('salary_history_id')
    )
    op.create_table('t_material_list',
    sa.Column('material_list_id', sa.Integer(), nullable=False),
    sa.Column('center_material_id', sa.Integer(), nullable=True),
    sa.Column('sales_item_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=28), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('item_group', sa.String(length=64), nullable=False),
    sa.Column('order_line_num', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['sales_item_id'], ['t_sales_items.sales_item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('material_list_id')
    )
    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_material_list_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_qc_work_order',
    sa.Column('qc_work_order_id', sa.Integer(), nullable=False),
    sa.Column('qc_work_order_code', sa.String(length=50), nullable=True),
    sa.Column('sales_item_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INPROGRESS', 'PASSED', name='qcworkorderstatus'), nullable=False),
    sa.Column('qc_date', sa.DateTime(), nullable=True),
    sa.Column('qc_by', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['sales_item_id'], ['t_sales_items.sales_item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qc_work_order_id')
    )
    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_qc_work_order_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_work_order',
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('doc_num', sa.Integer(), nullable=False),
    sa.Column('work_order_code', sa.String(length=50), nullable=True),
    sa.Column('doc_entry', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('READY', 'INPROGRESS', 'WAIT_TEST', 'TESTING', 'COMPLETED', name='workorderstatus'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sales_item_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['doc_entry'], ['t_sales_order.doc_entry'], ),
    sa.ForeignKeyConstraint(['sales_item_id'], ['t_sales_items.sales_item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_order_id')
    )
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_work_order_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_item_component',
    sa.Column('item_component_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('component_name', sa.String(length=255), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('img_url', sa.String(length=500), nullable=True),
    sa.Column('component_template_id', sa.Integer(), nullable=True),
    sa.Column('doc_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['component_template_id'], ['m_component_template.component_template_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['t_work_order.work_order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_component_id')
    )
    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_item_component_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_material_transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('material_list_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INIT', 'ADD', 'REMOVE', name='materialtransactiontype'), nullable=False),
    sa.Column('related_document_code', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_list_id'], ['t_material_list.material_list_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('t_picking_request_item',
    sa.Column('picking_request_item_id', sa.Integer(), nullable=False),
    sa.Column('picking_request_id', sa.Integer(), nullable=False),
    sa.Column('sales_item_id', sa.Integer(), nullable=True),
    sa.Column('material_list_id', sa.Integer(), nullable=True),
    sa.Column('order_line_num', sa.Integer(), nullable=True),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['material_list_id'], ['t_material_list.material_list_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['picking_request_id'], ['t_picking_request.picking_request_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_item_id'], ['t_sales_items.sales_item_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('picking_request_item_id')
    )
    with op.batch_alter_table('t_picking_request_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_picking_request_item_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_qc_form',
    sa.Column('qc_form_id', sa.Integer(), nullable=False),
    sa.Column('qc_work_order_id', sa.Integer(), nullable=False),
    sa.Column('std_ptt', sa.Boolean(), nullable=True),
    sa.Column('std_chevron', sa.Boolean(), nullable=True),
    sa.Column('std_valeur', sa.Boolean(), nullable=True),
    sa.Column('std_ophir', sa.Boolean(), nullable=True),
    sa.Column('std_three_spec', sa.Boolean(), nullable=True),
    sa.Column('std_others', sa.Boolean(), nullable=True),
    sa.Column('std_others_text', sa.String(length=200), nullable=True),
    sa.Column('cert_inhouse', sa.Boolean(), nullable=True),
    sa.Column('cert_third_party', sa.Boolean(), nullable=True),
    sa.Column('cert_ndt', sa.Boolean(), nullable=True),
    sa.Column('cert_others', sa.Boolean(), nullable=True),
    sa.Column('cert_others_text', sa.String(length=200), nullable=True),
    sa.Column('serial_tag', sa.Boolean(), nullable=True),
    sa.Column('serial_imprint', sa.Boolean(), nullable=True),
    sa.Column('serial_continue', sa.Boolean(), nullable=True),
    sa.Column('serial_others', sa.Boolean(), nullable=True),
    sa.Column('serial_others_text', sa.String(length=200), nullable=True),
    sa.Column('general_remark', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('customer_receipt_number', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qc_work_order_id'], ['t_qc_work_order.qc_work_order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qc_form_id'),
    sa.UniqueConstraint('qc_work_order_id')
    )
    op.create_table('t_qc_item',
    sa.Column('qc_item_id', sa.Integer(), nullable=False),
    sa.Column('qc_work_order_id', sa.Integer(), nullable=False),
    sa.Column('item_order', sa.Integer(), nullable=True),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('wll', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('serial_no', sa.String(length=200), nullable=True),
    sa.Column('item_remark', sa.String(length=500), nullable=True),
    sa.Column('material_list_id', sa.Integer(), nullable=True),
    sa.Column('required_qty', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_list_id'], ['t_material_list.material_list_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qc_work_order_id'], ['t_qc_work_order.qc_work_order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qc_item_id')
    )
    op.create_table('t_test_result',
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('test_result_code', sa.String(length=100), nullable=True),
    sa.Column('qc_work_order_id', sa.Integer(), nullable=True),
    sa.Column('claimed_qty', sa.Integer(), nullable=False),
    sa.Column('session_status', sa.Enum('PENDING', 'INPROGRESS', 'PAUSED', 'COMPLETED', name='testsessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('test_method', sa.String(length=255), nullable=True),
    sa.Column('standard_reference', sa.String(length=255), nullable=True),
    sa.Column('overall_status', sa.Enum('PASSED', 'FAILED', name='testresultstatus'), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['qc_work_order_id'], ['t_qc_work_order.qc_work_order_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('test_result_id')
    )
    with op.batch_alter_table('t_test_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_test_result_branch_id'), ['branch_id'], unique=False)

    op.create_table('m_component_template_section_data',
    sa.Column('section_data_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_type', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('section_key', sa.String(length=255), nullable=False),
    sa.Column('item_component_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_component_id'], ['t_item_component.item_component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_data_id')
    )
    op.create_table('t_component_material_usage',
    sa.Column('usage_id', sa.Integer(), nullable=False),
    sa.Column('item_component_id', sa.Integer(), nullable=False),
    sa.Column('material_list_id', sa.Integer(), nullable=False),
    sa.Column('quantity_used', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['item_component_id'], ['t_item_component.item_component_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_list_id'], ['t_material_list.material_list_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usage_id')
    )
    with op.batch_alter_table('t_component_material_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_component_material_usage_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_picking_item_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picking_request_item_id', sa.Integer(), nullable=False),
    sa.Column('delta_qty', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('MISCOUNT', 'SPILLAGE', 'CORRECTION', 'REALLOCATE', 'OTHER', name='pickingitemadjustmentreason'), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('counterparty_picking_request_item_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['counterparty_picking_request_item_id'], ['t_picking_request_item.picking_request_item_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['picking_request_item_id'], ['t_picking_request_item.picking_request_item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('t_picking_item_adjustment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_picking_item_adjustment_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_test_result_assignment',
    sa.Column('test_result_assignment_id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('from_time', sa.DateTime(), nullable=False),
    sa.Column('to_time', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['m_employee.employee_id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['t_test_result.test_result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_result_assignment_id')
    )
    with op.batch_alter_table('t_test_result_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_test_result_assignment_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_test_result_break',
    sa.Column('break_id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('break_start', sa.DateTime(), nullable=False),
    sa.Column('break_end', sa.DateTime(), nullable=True),
    sa.Column('break_type', sa.Enum('LUNCHBREAK', 'RESTBREAK', 'OTHER', name='breaktype'), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['t_test_result.test_result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('break_id')
    )
    with op.batch_alter_table('t_test_result_break', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_test_result_break_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_test_result_cost',
    sa.Column('cost_id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('material_cost', sa.Float(), nullable=True),
    sa.Column('depreciation_cost', sa.Float(), nullable=True),
    sa.Column('maintenance_cost', sa.Float(), nullable=True),
    sa.Column('base_labor_cost', sa.Float(), nullable=True),
    sa.Column('day_labor_cost', sa.Float(), nullable=True),
    sa.Column('ot_labor_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['t_test_result.test_result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cost_id'),
    sa.UniqueConstraint('test_result_id')
    )
    with op.batch_alter_table('t_test_result_cost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_test_result_cost_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_test_result_item',
    sa.Column('test_result_item_id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=200), nullable=True),
    sa.Column('wll_measured', sa.Float(), nullable=True),
    sa.Column('load_test_value', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('result', sa.Enum('PASSED', 'FAILED', name='testresultstatus'), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['t_test_result.test_result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_result_item_id')
    )
    with op.batch_alter_table('t_test_result_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_test_result_item_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_test_result_machine',
    sa.Column('test_result_machine_id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('from_time', sa.DateTime(), nullable=False),
    sa.Column('to_time', sa.DateTime(), nullable=True),
    sa.Column('allocated_maintenance_cost', sa.Float(), nullable=True),
    sa.Column('depreciation_per_second', sa.Float(), nullable=False),
    sa.Column('maintenance_rate_per_second', sa.Float(), nullable=False),
    sa.Column('depreciation_cost', sa.Float(), nullable=True),
    sa.Column('maintenance_cost', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['m_machine.machine_id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['t_test_result.test_result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_result_machine_id')
    )
    with op.batch_alter_table('t_test_result_machine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_test_result_machine_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_test_result_required_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('qc_item_id', sa.Integer(), nullable=True),
    sa.Column('material_list_id', sa.Integer(), nullable=True),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('required_qty', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('qty_consumed_actual', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['material_list_id'], ['t_material_list.material_list_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qc_item_id'], ['t_qc_item.qc_item_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_result_id'], ['t_test_result.test_result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('t_test_result_required_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_test_result_required_item_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_work_run',
    sa.Column('work_run_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('usable_qty', sa.Integer(), nullable=True),
    sa.Column('completion_remark', sa.String(length=500), nullable=True),
    sa.Column('wms_pick_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INPROGRESS', 'PAUSED', 'COMPLETED', name='workrunstatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('rework_source_test_result_id', sa.Integer(), nullable=True),
    sa.Column('qty_from_failed', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['rework_source_test_result_id'], ['t_test_result.test_result_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['t_work_order.work_order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_run_id')
    )
    with op.batch_alter_table('t_work_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_work_run_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_qc_check_item',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('qc_certification_id', sa.Integer(), nullable=False),
    sa.Column('sales_item_id', sa.Integer(), nullable=True),
    sa.Column('test_result_item_id', sa.Integer(), nullable=True),
    sa.Column('item_no', sa.String(length=50), nullable=True),
    sa.Column('test_number', sa.String(length=255), nullable=False),
    sa.Column('ref_number', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('wll', sa.Float(), nullable=True),
    sa.Column('load_test', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qc_certification_id'], ['t_qc_certification.qc_certification_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_item_id'], ['t_sales_items.sales_item_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_result_item_id'], ['t_test_result_item.test_result_item_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_table('t_test_result_picking_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('picking_request_item_id', sa.Integer(), nullable=False),
    sa.Column('test_result_required_item_id', sa.Integer(), nullable=True),
    sa.Column('qty_allocated', sa.Integer(), nullable=False),
    sa.Column('qty_consumed', sa.Integer(), nullable=True),
    sa.Column('allocation_mode', sa.Enum('AUTO', 'MANUAL', name='allocationmode'), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['picking_request_item_id'], ['t_picking_request_item.picking_request_item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_result_id'], ['t_test_result.test_result_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_result_required_item_id'], ['t_test_result_required_item.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_test_result_work_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('work_run_id', sa.Integer(), nullable=False),
    sa.Column('qty_from_run', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_result_id'], ['t_test_result.test_result_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_run_id'], ['t_work_run.work_run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_work_run_assignment',
    sa.Column('work_run_assignment_id', sa.Integer(), nullable=False),
    sa.Column('work_run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('from_time', sa.DateTime(), nullable=False),
    sa.Column('to_time', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['m_employee.employee_id'], ),
    sa.ForeignKeyConstraint(['work_run_id'], ['t_work_run.work_run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_run_assignment_id')
    )
    with op.batch_alter_table('t_work_run_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_work_run_assignment_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_work_run_break',
    sa.Column('break_id', sa.Integer(), nullable=False),
    sa.Column('work_run_id', sa.Integer(), nullable=False),
    sa.Column('break_start', sa.DateTime(), nullable=False),
    sa.Column('break_end', sa.DateTime(), nullable=True),
    sa.Column('break_type', sa.Enum('LUNCHBREAK', 'RESTBREAK', 'OTHER', name='breaktype'), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['work_run_id'], ['t_work_run.work_run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('break_id')
    )
    with op.batch_alter_table('t_work_run_break', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_work_run_break_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_work_run_cost',
    sa.Column('cost_id', sa.Integer(), nullable=False),
    sa.Column('work_run_id', sa.Integer(), nullable=False),
    sa.Column('material_cost', sa.Float(), nullable=True),
    sa.Column('depreciation_cost', sa.Float(), nullable=True),
    sa.Column('maintenance_cost', sa.Float(), nullable=True),
    sa.Column('base_labor_cost', sa.Float(), nullable=True),
    sa.Column('day_labor_cost', sa.Float(), nullable=True),
    sa.Column('ot_labor_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['work_run_id'], ['t_work_run.work_run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cost_id'),
    sa.UniqueConstraint('work_run_id')
    )
    with op.batch_alter_table('t_work_run_cost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_work_run_cost_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_work_run_machine',
    sa.Column('work_run_machine_id', sa.Integer(), nullable=False),
    sa.Column('work_run_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('from_time', sa.DateTime(), nullable=False),
    sa.Column('to_time', sa.DateTime(), nullable=True),
    sa.Column('allocated_maintenance_cost', sa.Float(), nullable=True),
    sa.Column('depreciation_per_second', sa.Float(), nullable=False),
    sa.Column('maintenance_rate_per_second', sa.Float(), nullable=False),
    sa.Column('depreciation_cost', sa.Float(), nullable=True),
    sa.Column('maintenance_cost', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['m_machine.machine_id'], ),
    sa.ForeignKeyConstraint(['work_run_id'], ['t_work_run.work_run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_run_machine_id')
    )
    with op.batch_alter_table('t_work_run_machine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_work_run_machine_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_work_run_required_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_run_id', sa.Integer(), nullable=False),
    sa.Column('material_list_id', sa.Integer(), nullable=True),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('qty_consumed_actual', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['material_list_id'], ['t_material_list.material_list_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_run_id'], ['t_work_run.work_run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('t_work_run_required_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_work_run_required_item_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_work_run_rework_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rework_work_run_id', sa.Integer(), nullable=False),
    sa.Column('source_work_run_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rework_work_run_id'], ['t_work_run.work_run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_work_run_id'], ['t_work_run.work_run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_work_run_transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('work_run_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SENT_TO_TESTING', 'DEFECT_CONSUMED', name='workruntransactiontype'), nullable=False),
    sa.Column('related_document_code', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ),
    sa.ForeignKeyConstraint(['work_run_id'], ['t_work_run.work_run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('t_work_run_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_work_run_transaction_branch_id'), ['branch_id'], unique=False)

    op.create_table('t_work_run_picking_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_run_id', sa.Integer(), nullable=False),
    sa.Column('picking_request_item_id', sa.Integer(), nullable=False),
    sa.Column('work_run_required_item_id', sa.Integer(), nullable=True),
    sa.Column('qty_allocated', sa.Integer(), nullable=False),
    sa.Column('qty_consumed', sa.Integer(), nullable=True),
    sa.Column('allocation_mode', sa.Enum('AUTO', 'MANUAL', name='allocationmode'), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['picking_request_item_id'], ['t_picking_request_item.picking_request_item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_run_id'], ['t_work_run.work_run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_run_required_item_id'], ['t_work_run_required_item.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_work_run_picking_item')
    with op.batch_alter_table('t_work_run_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_transaction_branch_id'))

    op.drop_table('t_work_run_transaction')
    op.drop_table('t_work_run_rework_source')
    with op.batch_alter_table('t_work_run_required_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_required_item_branch_id'))

    op.drop_table('t_work_run_required_item')
    with op.batch_alter_table('t_work_run_machine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_machine_branch_id'))

    op.drop_table('t_work_run_machine')
    with op.batch_alter_table('t_work_run_cost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_cost_branch_id'))

    op.drop_table('t_work_run_cost')
    with op.batch_alter_table('t_work_run_break', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_break_branch_id'))

    op.drop_table('t_work_run_break')
    with op.batch_alter_table('t_work_run_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_assignment_branch_id'))

    op.drop_table('t_work_run_assignment')
    op.drop_table('t_test_result_work_run')
    op.drop_table('t_test_result_picking_item')
    op.drop_table('t_qc_check_item')
    with op.batch_alter_table('t_work_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_branch_id'))

    op.drop_table('t_work_run')
    with op.batch_alter_table('t_test_result_required_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_test_result_required_item_branch_id'))

    op.drop_table('t_test_result_required_item')
    with op.batch_alter_table('t_test_result_machine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_test_result_machine_branch_id'))

    op.drop_table('t_test_result_machine')
    with op.batch_alter_table('t_test_result_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_test_result_item_branch_id'))

    op.drop_table('t_test_result_item')
    with op.batch_alter_table('t_test_result_cost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_test_result_cost_branch_id'))

    op.drop_table('t_test_result_cost')
    with op.batch_alter_table('t_test_result_break', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_test_result_break_branch_id'))

    op.drop_table('t_test_result_break')
    with op.batch_alter_table('t_test_result_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_test_result_assignment_branch_id'))

    op.drop_table('t_test_result_assignment')
    with op.batch_alter_table('t_picking_item_adjustment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_picking_item_adjustment_branch_id'))

    op.drop_table('t_picking_item_adjustment')
    with op.batch_alter_table('t_component_material_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_component_material_usage_branch_id'))

    op.drop_table('t_component_material_usage')
    op.drop_table('m_component_template_section_data')
    with op.batch_alter_table('t_test_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_test_result_branch_id'))

    op.drop_table('t_test_result')
    op.drop_table('t_qc_item')
    op.drop_table('t_qc_form')
    with op.batch_alter_table('t_picking_request_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_picking_request_item_branch_id'))

    op.drop_table('t_picking_request_item')
    op.drop_table('t_material_transaction')
    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_item_component_branch_id'))

    op.drop_table('t_item_component')
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_order_branch_id'))

    op.drop_table('t_work_order')
    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_qc_work_order_branch_id'))

    op.drop_table('t_qc_work_order')
    with op.batch_alter_table('t_material_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_material_list_branch_id'))

    op.drop_table('t_material_list')
    op.drop_table('t_employee_salary_history')
    op.drop_table('m_employee_shift')
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_sales_items_branch_id'))
        batch_op.drop_index('ix_sales_items_doc_entry_test')
        batch_op.drop_index('ix_sales_items_doc_entry_produce')

    op.drop_table('t_sales_items')
    op.drop_table('t_qc_certification')
    with op.batch_alter_table('t_picking_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_picking_request_branch_id'))

    op.drop_table('t_picking_request')
    with op.batch_alter_table('t_machine_maintenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_machine_maintenance_branch_id'))

    op.drop_table('t_machine_maintenance')
    op.drop_table('map_user_branch')
    op.drop_table('m_role_permission')
    op.drop_table('m_employee')
    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_sales_order_branch_id'))

    op.drop_table('t_sales_order')
    op.drop_table('m_user')
    op.drop_table('m_phase_template_item')
    op.drop_table('m_permission')
    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_m_machine_branch_id'))

    op.drop_table('m_machine')
    op.drop_table('m_gen_number_config')
    op.drop_table('t_token_list')
    op.drop_table('m_shift')
    op.drop_table('m_role')
    op.drop_table('m_phase_template')
    op.drop_table('m_operation_cost_monthly')
    op.drop_table('m_module')
    op.drop_table('m_machine_type')
    op.drop_table('m_holiday')
    op.drop_table('m_document_code_list')
    op.drop_table('m_component_template')
    op.drop_table('m_branch')
    # ### end Alembic commands ###
