"""empty message

Revision ID: b1cf475d0ed7
Revises: 827e0000324e
Create Date: 2026-02-20 11:31:48.911792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1cf475d0ed7'
down_revision = '827e0000324e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('UNEMPLOYED', 'ACTIVE', 'ON_LEAVE', 'SUSPENDED'),
               type_=sa.Enum('UNEMPLOYED', 'ACTIVE', 'ONLEAVE', 'SUSPENDED', name='employeestatus'),
               existing_nullable=False)

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('READY', 'IN_PROGRESS', 'COMPLETED'),
               type_=sa.Enum('READY', 'INPROGRESS', 'COMPLETED', name='workorderstatus'),
               existing_nullable=False)

    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.alter_column('phase_status',
               existing_type=mysql.ENUM('PENDING', 'IN_PROGRESS', 'PAUSED', 'COMPLETED'),
               type_=sa.Enum('PENDING', 'INPROGRESS', 'PAUSED', 'COMPLETED', name='phasestatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.alter_column('phase_status',
               existing_type=sa.Enum('PENDING', 'INPROGRESS', 'PAUSED', 'COMPLETED', name='phasestatus'),
               type_=mysql.ENUM('PENDING', 'IN_PROGRESS', 'PAUSED', 'COMPLETED'),
               existing_nullable=False)

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('READY', 'INPROGRESS', 'COMPLETED', name='workorderstatus'),
               type_=mysql.ENUM('READY', 'IN_PROGRESS', 'COMPLETED'),
               existing_nullable=False)

    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('UNEMPLOYED', 'ACTIVE', 'ONLEAVE', 'SUSPENDED', name='employeestatus'),
               type_=mysql.ENUM('UNEMPLOYED', 'ACTIVE', 'ON_LEAVE', 'SUSPENDED'),
               existing_nullable=False)

    # ### end Alembic commands ###
