"""empty message

Revision ID: b27f593af741
Revises: 6b505740d3f5
Create Date: 2026-04-08 09:48:50.671716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27f593af741'
down_revision = '6b505740d3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_machine_type',
    sa.Column('machine_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('type_description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('machine_type_id')
    )
    op.create_table('m_phase_template',
    sa.Column('phase_template_id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('phase_template_id')
    )
    op.create_table('m_phase_template_item',
    sa.Column('phase_template_item_id', sa.Integer(), nullable=False),
    sa.Column('phase_template_id', sa.Integer(), nullable=False),
    sa.Column('phase_name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('machine_type_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_type_id'], ['m_machine_type.machine_type_id'], ),
    sa.ForeignKeyConstraint(['phase_template_id'], ['m_phase_template.phase_template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phase_template_item_id')
    )
    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'm_machine_type', ['machine_type_id'], ['machine_type_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('machine_type_id')

    op.drop_table('m_phase_template_item')
    op.drop_table('m_phase_template')
    op.drop_table('m_machine_type')
    # ### end Alembic commands ###
