"""empty message

Revision ID: b30391a72aeb
Revises: 05cb554d2f09
Create Date: 2026-03-17 13:55:39.140394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b30391a72aeb'
down_revision = '05cb554d2f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 't_work_run', ['work_run_id'], ['work_run_id'], ondelete='CASCADE')
        batch_op.drop_column('work_order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_order_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
