"""empty message

Revision ID: b810a2582e0e
Revises: b83aaa53d717
Create Date: 2026-04-12 17:38:16.034349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b810a2582e0e'
down_revision = 'b83aaa53d717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_test_result_picking_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('picking_request_item_id', sa.Integer(), nullable=False),
    sa.Column('qty_consumed', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['picking_request_item_id'], ['t_picking_request_item.picking_request_item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_result_id'], ['t_test_result.test_result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('t_test_result_picking_request')
    with op.batch_alter_table('t_picking_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_entry', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('t_picking_request_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_picking_request_sales_item'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('t_picking_request_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_sales_order', ['doc_entry'], ['doc_entry'], ondelete='SET NULL')
        batch_op.drop_column('work_run_id')
        batch_op.drop_column('test_result_id')
        batch_op.drop_column('sales_item_id')
        batch_op.drop_column('request_type')

    with op.batch_alter_table('t_picking_request_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('material_list_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_line_num', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 't_material_list', ['material_list_id'], ['material_list_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 't_sales_items', ['sales_item_id'], ['sales_item_id'], ondelete='SET NULL')

    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.drop_column('unit_code')

    with op.batch_alter_table('t_work_run_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_run_assignment_branch_id'))

    with op.batch_alter_table('t_work_run_break', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_run_break_branch_id'))

    with op.batch_alter_table('t_work_run_machine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_run_machine_branch_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_run_machine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_run_machine_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('t_work_run_break', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_run_break_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('t_work_run_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_run_assignment_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_code', mysql.VARCHAR(length=28), nullable=True))

    with op.batch_alter_table('t_picking_request_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_line_num')
        batch_op.drop_column('material_list_id')
        batch_op.drop_column('sales_item_id')

    with op.batch_alter_table('t_picking_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_type', mysql.ENUM('WORK_RUN', 'TEST_RESULT', 'SALES_ITEM'), nullable=False))
        batch_op.add_column(sa.Column('sales_item_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('test_result_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('work_run_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_picking_request_ibfk_1'), 't_test_result', ['test_result_id'], ['test_result_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_picking_request_sales_item'), 't_sales_items', ['sales_item_id'], ['sales_item_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('t_picking_request_ibfk_2'), 't_work_run', ['work_run_id'], ['work_run_id'], ondelete='SET NULL')
        batch_op.drop_column('doc_entry')

    op.create_table('t_test_result_picking_request',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_result_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('picking_request_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qty_from_picking', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['picking_request_id'], ['t_picking_request.picking_request_id'], name=op.f('t_test_result_picking_request_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_result_id'], ['t_test_result.test_result_id'], name=op.f('t_test_result_picking_request_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('t_test_result_picking_item')
    # ### end Alembic commands ###
