"""recheck

Revision ID: bd8deb8fe400
Revises: a18bd8007b03
Create Date: 2026-04-27 11:16:19.796048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd8deb8fe400'
down_revision = 'a18bd8007b03'
branch_labels = None
depends_on = None


def _column_exists(conn, table, column):
    result = conn.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.COLUMNS "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :t AND COLUMN_NAME = :c"
    ), {"t": table, "c": column})
    return result.scalar() > 0



def _index_exists(conn, table, index_name):
    result = conn.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.STATISTICS "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :t AND INDEX_NAME = :i"
    ), {"t": table, "i": index_name})
    return result.scalar() > 0


def upgrade():
    conn = op.get_bind()

    if not _column_exists(conn, 't_picking_item_adjustment', 'counterparty_picking_request_item_id'):
        with op.batch_alter_table('t_picking_item_adjustment', schema=None) as batch_op:
            batch_op.add_column(sa.Column('counterparty_picking_request_item_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 't_picking_request_item', ['counterparty_picking_request_item_id'], ['picking_request_item_id'], ondelete='SET NULL')

    if not _column_exists(conn, 't_picking_request', 'is_reallocation'):
        with op.batch_alter_table('t_picking_request', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_reallocation', sa.Boolean(), nullable=False))

    # Modify nullable with FK checks disabled to avoid MySQL FK constraint conflicts
    conn.execute(sa.text("SET FOREIGN_KEY_CHECKS=0"))
    conn.execute(sa.text("ALTER TABLE `t_work_run_cost` MODIFY COLUMN `branch_id` INT NOT NULL"))
    conn.execute(sa.text("SET FOREIGN_KEY_CHECKS=1"))

    if not _index_exists(conn, 't_work_run_cost', 'ix_t_work_run_cost_branch_id'):
        with op.batch_alter_table('t_work_run_cost', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_t_work_run_cost_branch_id'), ['branch_id'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_run_cost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_cost_branch_id'))
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('t_picking_request', schema=None) as batch_op:
        batch_op.drop_column('is_reallocation')

    with op.batch_alter_table('t_picking_item_adjustment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('counterparty_picking_request_item_id')

    # ### end Alembic commands ###
