"""fix nullable test-produce

Revision ID: c195bd62ffa2
Revises: 184234e7c6b2
Create Date: 2026-04-06 14:59:04.634504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c195bd62ffa2'
down_revision = '184234e7c6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.alter_column('produce',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('test',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.alter_column('test',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('produce',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
