"""empty message

Revision ID: c297c0928965
Revises: 3b0e03b732d4
Create Date: 2026-02-25 17:04:18.243549

"""
from alembic import op
import sqlalchemy as sa

from migrations.utils import column_exists


# revision identifiers, used by Alembic.
revision = 'c297c0928965'
down_revision = '3b0e03b732d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        if not column_exists('t_item_component', 'component_name'):
            batch_op.add_column(sa.Column('component_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        batch_op.drop_column('component_name')

    # ### end Alembic commands ###
