"""Add m_branch and map_user_branch tables

Revision ID: cba47c432ed4
Revises: 82519a919bef
Create Date: 2026-03-16 10:34:12.886598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba47c432ed4'
down_revision = '82519a919bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_branch',
    sa.Column('branch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_code', sa.String(length=20), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('branch_id'),
    sa.UniqueConstraint('branch_code')
    )
    op.create_table('map_user_branch',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['m_branch.branch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['m_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'branch_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_user_branch')
    op.drop_table('m_branch')
    # ### end Alembic commands ###
