"""empty message

Revision ID: cd92aaa0d0d6
Revises: a7c501b99c70
Create Date: 2026-03-19 09:33:35.677727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd92aaa0d0d6'
down_revision = 'a7c501b99c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_component_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sections', sa.JSON(), nullable=False))
        batch_op.drop_column('config')

    with op.batch_alter_table('m_component_template_section_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_type', sa.String(length=255), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_component_template_section_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('section_type')

    with op.batch_alter_table('m_component_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', mysql.JSON(), nullable=False))
        batch_op.drop_column('sections')

    # ### end Alembic commands ###
