"""Inventory_transaction

Revision ID: ce9d1d085d28
Revises: ad561750863e
Create Date: 2026-03-04 11:39:38.929367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce9d1d085d28'
down_revision = 'ad561750863e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_component_material_usage')
    op.drop_table('t_item_component')
    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 't_sales_items', ['sales_item_id'], ['sales_item_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('t_item_component',
    sa.Column('item_component_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('component_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['t_work_order.work_order_id'], name=op.f('t_item_component_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_component_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_component_material_usage',
    sa.Column('usage_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_component_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_list_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_used', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['item_component_id'], ['t_item_component.item_component_id'], name=op.f('t_component_material_usage_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_list_id'], ['t_material_list.material_list_id'], name=op.f('t_component_material_usage_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usage_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
