"""empty message

Revision ID: cecb53e907f1
Revises: fe21e2325aca
Create Date: 2026-02-23 15:48:37.777013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cecb53e907f1'
down_revision = 'fe21e2325aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_sales_items_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('work_order_id')

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 't_sales_items', ['sales_item_id'], ['sales_item_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sales_item_id')

    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_order_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('t_sales_items_ibfk_2'), 't_work_order', ['work_order_id'], ['work_order_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
