"""add maintenance cost tracking to machine and work_run_machine

Revision ID: ced5dab8313d
Revises: 56932c5cafc4
Create Date: 2026-04-22 11:27:14.977400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced5dab8313d'
down_revision = '56932c5cafc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_maintenance_cost', sa.Float(), nullable=True))

    with op.batch_alter_table('t_work_run_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allocated_maintenance_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_run_machine', schema=None) as batch_op:
        batch_op.drop_column('allocated_maintenance_cost')

    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.drop_column('remaining_maintenance_cost')

    # ### end Alembic commands ###
