"""empty message

Revision ID: cf5bd903f1f8
Revises: fccdfbea2f71
Create Date: 2026-02-17 13:16:32.881204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf5bd903f1f8'
down_revision = 'fccdfbea2f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        batch_op.drop_column('slp_code')
        batch_op.drop_column('slp_name')
        batch_op.drop_column('group_code')
        batch_op.drop_column('bpl_code')
        batch_op.drop_column('bpl_name')
        batch_op.drop_column('card_name')
        batch_op.drop_column('group_name')
        batch_op.drop_column('card_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_code', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('group_name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('card_name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('bpl_name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('bpl_code', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('group_code', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('slp_name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('slp_code', mysql.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
