"""empty message

Revision ID: d134a2d684df
Revises: b30391a72aeb
Create Date: 2026-03-17 16:57:54.177315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd134a2d684df'
down_revision = 'b30391a72aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_component_option_type')
    with op.batch_alter_table('t_component_spec', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_item_component_spec'))

    op.drop_table('t_component_spec')
    op.drop_table('t_component_option')
    op.drop_table('t_component_spec_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_component_spec_type',
    sa.Column('component_spec_type_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('component_spec_type_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('spec_type', mysql.ENUM('boolean', 'decimal', 'text'), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('component_spec_type_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_component_option',
    sa.Column('component_option_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('component_option_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_component_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['component_option_type_id'], ['t_component_option_type.component_option_type_id'], name=op.f('t_component_option_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_component_id'], ['t_item_component.item_component_id'], name=op.f('t_component_option_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_option_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_component_spec',
    sa.Column('component_spec_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_component_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('component_spec_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_side', mysql.ENUM('top', 'bottom'), nullable=True),
    sa.Column('bool_value', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('decimal_value', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('text_value', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['component_spec_type_id'], ['t_component_spec_type.component_spec_type_id'], name=op.f('t_component_spec_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_component_id'], ['t_item_component.item_component_id'], name=op.f('t_component_spec_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_spec_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('t_component_spec', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_item_component_spec'), ['item_component_id', 'component_spec_type_id', 'end_side'], unique=True)

    op.create_table('t_component_option_type',
    sa.Column('component_option_type_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('component_option_type_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('component_option_type_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
