"""gen_number

Revision ID: d25e6d663da0
Revises: 884e940eedea
Create Date: 2026-03-23 10:12:50.054846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25e6d663da0'
down_revision = '884e940eedea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_picking_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picking_request_code', sa.String(length=100), nullable=True))

    with op.batch_alter_table('t_test_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_result_code', sa.String(length=100), nullable=True))

    with op.batch_alter_table('t_work_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_run', schema=None) as batch_op:
        batch_op.drop_column('lot_number')

    with op.batch_alter_table('t_test_result', schema=None) as batch_op:
        batch_op.drop_column('test_result_code')

    with op.batch_alter_table('t_picking_request', schema=None) as batch_op:
        batch_op.drop_column('picking_request_code')

    # ### end Alembic commands ###
