"""add form_data to qc_work_order

Revision ID: d2a6de498cf3
Revises: 75b0e1e0822d
Create Date: 2026-02-23 14:01:54.706891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a6de498cf3'
down_revision = '75b0e1e0822d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_qc_work_order', schema=None) as batch_op:
        batch_op.drop_column('form_data')

    # ### end Alembic commands ###
