"""add-status-wait-test

Revision ID: d3e5fc3abbc2
Revises: d2a6de498cf3
Create Date: 2026-02-23 15:20:44.965415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'd3e5fc3abbc2'
down_revision = 'd2a6de498cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('READY', 'INPROGRESS', 'COMPLETED'),
               type_=sa.Enum('READY', 'INPROGRESS', 'WAIT_TEST', 'TESTING', 'COMPLETED', name='workorderstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('READY', 'INPROGRESS', 'WAIT_TEST', 'TESTING', 'COMPLETED', name='workorderstatus'),
               type_=mysql.ENUM('READY', 'INPROGRESS', 'COMPLETED'),
               existing_nullable=False)
    # ### end Alembic commands ###
