"""added sales order detail

Revision ID: d54570c20185
Revises: e36147ce9dc5
Create Date: 2026-02-17 11:14:09.116758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd54570c20185'
down_revision = 'e36147ce9dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('UNEMPLOYED', 'PROBATION', 'FULL_TIME', 'RESIGNED', 'TERMINATED', name='employee_status_enum'),
               existing_nullable=False)

    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('card_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('slp_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('slp_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('bpl_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('bpl_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('group_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('group_name', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_order', schema=None) as batch_op:
        batch_op.drop_column('group_name')
        batch_op.drop_column('group_code')
        batch_op.drop_column('bpl_name')
        batch_op.drop_column('bpl_code')
        batch_op.drop_column('slp_name')
        batch_op.drop_column('slp_code')
        batch_op.drop_column('card_name')
        batch_op.drop_column('card_code')

    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('UNEMPLOYED', 'PROBATION', 'FULL_TIME', 'RESIGNED', 'TERMINATED', name='employee_status_enum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###