"""empty message

Revision ID: d8a83ec85856
Revises: 3279f5f400e9
Create Date: 2026-04-18 13:04:57.059277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a83ec85856'
down_revision = '3279f5f400e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_role_permission', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_role_permission', ['role_id', 'permission_id'])

    with op.batch_alter_table('t_test_result_picking_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allocation_mode', sa.Enum('AUTO', 'MANUAL', name='allocationmode'), nullable=False))

    with op.batch_alter_table('t_work_run_picking_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allocation_mode', sa.Enum('AUTO', 'MANUAL', name='allocationmode'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_run_picking_item', schema=None) as batch_op:
        batch_op.drop_column('allocation_mode')

    with op.batch_alter_table('t_test_result_picking_item', schema=None) as batch_op:
        batch_op.drop_column('allocation_mode')

    with op.batch_alter_table('m_role_permission', schema=None) as batch_op:
        batch_op.drop_constraint('uq_role_permission', type_='unique')

    # ### end Alembic commands ###
