"""add-qc-cert

Revision ID: da8ed1cb0fb6
Revises: 5445fbfb0f48
Create Date: 2026-02-24 11:26:51.337405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8ed1cb0fb6'
down_revision = '5445fbfb0f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_qc_certification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorize_signature', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_qc_certification', schema=None) as batch_op:
        batch_op.drop_column('authorize_signature')

    # ### end Alembic commands ###
