"""empty message

Revision ID: daf99f430b4c
Revises: d134a2d684df
Create Date: 2026-03-18 11:50:32.973878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf99f430b4c'
down_revision = 'd134a2d684df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_component_template',
    sa.Column('component_template_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('component_template_id')
    )
    op.create_table('t_component_template_section_data',
    sa.Column('section_data_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('item_component_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_component_id'], ['t_item_component.item_component_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_data_id')
    )
    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'm_component_template', ['component_template_id'], ['component_template_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_item_component', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('component_template_id')

    op.drop_table('t_component_template_section_data')
    op.drop_table('m_component_template')
    # ### end Alembic commands ###
