"""empty message

Revision ID: dd328a3cf3c2
Revises: 3983c653708c
Create Date: 2026-02-06 13:17:24.053815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd328a3cf3c2'
down_revision = '3983c653708c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokenlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('jwt_id'))

    op.drop_table('tokenlist')
    with op.batch_alter_table('m_module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('m_permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('module_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'm_module', ['module_id'], ['module_id'], ondelete='CASCADE')

    with op.batch_alter_table('m_role', schema=None) as batch_op:
        batch_op.alter_column('active_flag',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.create_unique_constraint(None, ['role_name'])

    with op.batch_alter_table('m_role_permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('m_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('m_user_m_role_FK'))
        batch_op.create_foreign_key(None, 'm_role', ['role_id'], ['role_id'], onupdate='CASCADE')

    with op.batch_alter_table('t_token_list', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_token_list_m_user_FK'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_token_list', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('t_token_list_m_user_FK'), 'm_user', ['user_id'], ['user_id'])

    with op.batch_alter_table('m_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('m_user_m_role_FK'), ['role_id'], unique=False)

    with op.batch_alter_table('m_role_permission', schema=None) as batch_op:
        batch_op.drop_column('updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('m_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('active_flag',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('m_permission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('module_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('m_module', schema=None) as batch_op:
        batch_op.drop_column('updated_date')
        batch_op.drop_column('created_date')

    op.create_table('tokenlist',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jwt_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tokenlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('jwt_id'), ['jwt_id'], unique=True)

    # ### end Alembic commands ###
