"""empty message

Revision ID: ded945a4cac9
Revises: 99796086cdb8
Create Date: 2026-02-12 10:51:30.737564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded945a4cac9'
down_revision = '99796086cdb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 't_sales_items', ['sales_item_id'], ['sales_item_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sales_item_id')

    # ### end Alembic commands ###
