"""empty message

Revision ID: e36147ce9dc5
Revises: 0a25cff6a717
Create Date: 2026-02-17 09:48:36.755025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e36147ce9dc5'
down_revision = '0a25cff6a717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_salary_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_salary_history',
    sa.Column('salary_history_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_salary', mysql.FLOAT(), nullable=False),
    sa.Column('new_salary', mysql.FLOAT(), nullable=False),
    sa.Column('effective_date', mysql.DATETIME(), nullable=False),
    sa.Column('remark', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['m_employee.employee_id'], name=op.f('employee_salary_history_ibfk_1')),
    sa.PrimaryKeyConstraint('salary_history_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
