"""Add ForeignKey to BranchScopedMixin

Revision ID: e3fd6b598ab6
Revises: cba47c432ed4
Create Date: 2026-03-19 09:30:15.055265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fd6b598ab6'
down_revision = 'cba47c432ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_m_machine_branch_id'), ['branch_id'], unique=False)
        batch_op.create_foreign_key(None, 'm_branch', ['branch_id'], ['branch_id'])

    with op.batch_alter_table('t_machine_maintenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_t_machine_maintenance_branch_id'), ['branch_id'], unique=False)
        batch_op.create_foreign_key(None, 'm_branch', ['branch_id'], ['branch_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_machine_maintenance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_t_machine_maintenance_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('m_machine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_m_machine_branch_id'))
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
