"""empty message

Revision ID: e4c636d3a610
Revises: 69b70c869cf8
Create Date: 2026-04-15 22:13:37.864439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4c636d3a610'
down_revision = '69b70c869cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ---- t_test_result_required_item ----
#     with op.batch_alter_table('t_test_result_required_item') as batch_op:
#         batch_op.drop_constraint('t_test_result_required_item_ibfk_4', type_='foreignkey')

#     with op.batch_alter_table('t_test_result_required_item') as batch_op:
#         batch_op.alter_column('branch_id',
#             existing_type=mysql.INTEGER(),
#             nullable=False)

#     with op.batch_alter_table('t_test_result_required_item') as batch_op:
#         batch_op.create_foreign_key(
#             't_test_result_required_item_ibfk_4',
#             'm_branch',  # <-- parent table (FIX THIS if different)
#             ['branch_id'],
#             ['branch_id']
#         )
#         batch_op.create_index(
#             'ix_t_test_result_required_item_branch_id',
#             ['branch_id']
#         )

    # ---- t_work_run_required_item ----
#     with op.batch_alter_table('t_work_run_required_item') as batch_op:
#         batch_op.drop_constraint('t_work_run_required_item_ibfk_4', type_='foreignkey')

    with op.batch_alter_table('t_work_run_required_item') as batch_op:
        batch_op.alter_column('branch_id',
            existing_type=mysql.INTEGER(),
            nullable=False)

    with op.batch_alter_table('t_work_run_required_item') as batch_op:
        batch_op.create_foreign_key(
            't_work_run_required_item_ibfk_4',
            'm_branch',  # <-- verify this too
            ['branch_id'],
            ['branch_id']
        )
        batch_op.create_index(
            'ix_t_work_run_required_item_branch_id',
            ['branch_id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_run_required_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_required_item_branch_id'))
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('t_test_result_required_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_test_result_required_item_branch_id'))
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
