"""dev deploy

Revision ID: e677c81beaed
Revises: 4c9e64f3b855
Create Date: 2026-03-23 08:36:30.546290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e677c81beaed'
down_revision = '4c9e64f3b855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_operation_cost_monthly',
    sa.Column('operation_cost_monthly_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_cost_date', sa.Date(), nullable=False),
    sa.Column('depreciation_building_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('depreciation_building_period', sa.Integer(), nullable=False),
    sa.Column('depreciation_util_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('depreciation_util_period', sa.Integer(), nullable=False),
    sa.Column('office_rent_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('office_supplies_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('water_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('electricity_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('utility_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('operation_cost_monthly_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m_operation_cost_monthly')
    # ### end Alembic commands ###
