"""empty message

Revision ID: e974483f68a5
Revises: 149e5f6e90ff
Create Date: 2026-02-17 14:48:23.126803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e974483f68a5'
down_revision = '149e5f6e90ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_work_assignment_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_work_phase', ['work_phase_id'], ['work_phase_id'])

    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.alter_column('phase_status',
               existing_type=mysql.ENUM('รอดำเนินการ', 'กําลังดำเนินการ', 'หยุดชั่วคราว', 'เสร็จสิ้น', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.Enum('รอดําเนินการ', 'กําลังดําเนินการ', 'หยุดชั่วคราว', 'เสร็จสิ้น', name='phasestatus'),
               existing_nullable=False)

    with op.batch_alter_table('t_work_phase_break', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_work_phase_break_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_work_phase', ['work_phase_id'], ['work_phase_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase_break', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_work_phase_break_ibfk_1'), 't_work_phase', ['work_phase_id'], ['work_phase_id'], onupdate='RESTRICT', ondelete='CASCADE')

    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.alter_column('phase_status',
               existing_type=sa.Enum('รอดําเนินการ', 'กําลังดําเนินการ', 'หยุดชั่วคราว', 'เสร็จสิ้น', name='phasestatus'),
               type_=mysql.ENUM('รอดำเนินการ', 'กําลังดำเนินการ', 'หยุดชั่วคราว', 'เสร็จสิ้น', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               existing_nullable=False)

    with op.batch_alter_table('t_work_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_work_assignment_ibfk_1'), 't_work_phase', ['work_phase_id'], ['work_phase_id'], onupdate='RESTRICT', ondelete='CASCADE')

    # ### end Alembic commands ###
