"""empty message

Revision ID: f24736c7908b
Revises: 799e62318802
Create Date: 2026-04-10 10:26:32.500994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24736c7908b'
down_revision = '799e62318802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_name', sa.String(length=28), nullable=False))
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=False))

    with op.batch_alter_table('t_work_run_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_run_assignment_branch_id'))
        batch_op.create_index(batch_op.f('ix_t_work_run_assignment_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('t_work_run_break', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_run_break_branch_id'))
        batch_op.create_index(batch_op.f('ix_t_work_run_break_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('t_work_run_machine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_run_machine_branch_id'))
        batch_op.create_index(batch_op.f('ix_t_work_run_machine_branch_id'), ['branch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_run_machine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_machine_branch_id'))
        batch_op.create_index(batch_op.f('ix_work_run_machine_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('t_work_run_break', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_break_branch_id'))
        batch_op.create_index(batch_op.f('ix_work_run_break_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('t_work_run_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_work_run_assignment_branch_id'))
        batch_op.create_index(batch_op.f('ix_work_run_assignment_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('t_sales_items', schema=None) as batch_op:
        batch_op.drop_column('unit_id')
        batch_op.drop_column('unit_name')

    # ### end Alembic commands ###
