"""empty message

Revision ID: f76fd54199a0
Revises: ae8ad3f0b2bf
Create Date: 2026-02-13 10:51:31.111645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f76fd54199a0'
down_revision = 'ae8ad3f0b2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_work_items')
    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.alter_column('phase_status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('Pending', 'InProgress', 'Completed', 'Cancelled', name='work_phase_status'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.alter_column('phase_status',
               existing_type=sa.Enum('Pending', 'InProgress', 'Completed', 'Cancelled', name='work_phase_status'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    op.create_table('t_work_items',
    sa.Column('work_item_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_phase_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sales_item_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['sales_item_id'], ['t_sales_items.sales_item_id'], name=op.f('t_work_items_ibfk_2')),
    sa.ForeignKeyConstraint(['work_phase_id'], ['t_work_phase.work_phase_id'], name=op.f('t_work_items_ibfk_1')),
    sa.PrimaryKeyConstraint('work_item_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
