"""empty message

Revision ID: fccdfbea2f71
Revises: d54570c20185
Create Date: 2026-02-17 11:59:18.488696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fccdfbea2f71'
down_revision = 'd54570c20185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('UNEMPLOYED', 'PROBATION', 'FULL_TIME', 'RESIGNED', 'TERMINATED'),
               type_=sa.Enum('ว่างงาน', 'ทดลองงาน', 'พนักงานประจํา', 'ลาออก', 'เลิกจ้าง', name='employeestatus'),
               existing_nullable=False)

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('พร้อม', 'กําลังดําเนินการ', 'เสร็จสิ้น', name='workorderstatus'),
               existing_nullable=False)

    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.alter_column('phase_status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('รอดําเนินการ', 'กําลังดําเนินการ', 'หยุดชั่วคราว', 'เสร็จสิ้น', name='phasestatus'),
               existing_nullable=False)

    with op.batch_alter_table('t_work_phase_break', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Remark', sa.String(length=255), nullable=True))
        batch_op.alter_column('break_type',
               existing_type=mysql.ENUM('LUNCH', 'SHORT_BREAK', 'OTHER'),
               type_=sa.Enum('พักกลางวัน', 'พักเบรค', 'อื่นๆ', name='breaktype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_work_phase_break', schema=None) as batch_op:
        batch_op.alter_column('break_type',
               existing_type=sa.Enum('พักกลางวัน', 'พักเบรค', 'อื่นๆ', name='breaktype'),
               type_=mysql.ENUM('LUNCH', 'SHORT_BREAK', 'OTHER'),
               existing_nullable=False)
        batch_op.drop_column('Remark')

    with op.batch_alter_table('t_work_phase', schema=None) as batch_op:
        batch_op.alter_column('phase_status',
               existing_type=sa.Enum('รอดําเนินการ', 'กําลังดําเนินการ', 'หยุดชั่วคราว', 'เสร็จสิ้น', name='phasestatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('t_work_order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('พร้อม', 'กําลังดําเนินการ', 'เสร็จสิ้น', name='workorderstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ว่างงาน', 'ทดลองงาน', 'พนักงานประจํา', 'ลาออก', 'เลิกจ้าง', name='employeestatus'),
               type_=mysql.ENUM('UNEMPLOYED', 'PROBATION', 'FULL_TIME', 'RESIGNED', 'TERMINATED'),
               existing_nullable=False)

    # ### end Alembic commands ###