"""empty message

Revision ID: ffff117e3f6b
Revises: 33f00a3bd304
Create Date: 2026-02-11 09:50:04.662751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffff117e3f6b'
down_revision = '33f00a3bd304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('employee_last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('citizen_id', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['citizen_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('m_employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('status')
        batch_op.drop_column('citizen_id')
        batch_op.drop_column('employee_last_name')
        batch_op.drop_column('employee_first_name')

    # ### end Alembic commands ###
